### ISSUE TITLE
Padding between windows should not be doubled

### ISSUE THREAD

**Issue by ariefra** [zeroxoneafour/polonium#10]
**Describe the bug**
Padding between windows should not be doubled, they should have same value with edge padding.

**To Reproduce**
1. Press Meta+T
2. Adjust padding > 5
3. Press Meta+T again
4. Open up some windows
5. Observe Padding between windows, appears larger, 2*padding value

**Expected behavior**
Padding between windows should be overlapped to maintain simetri with edge padding

![image](https://github.com/zeroxoneafour/polonium/assets/16566652/813c8613-4c67-458e-bfc4-64b5f88cc85e)

**Comment by zeroxoneafour** [comment]
This is actually standard Kwin tiling behavior and I cannot do anything about it. But now you made me see it and I'll never be able to unsee it. I don't like it either.

**Comment by alvesvaren** [comment]
https://invent.kde.org/plasma/kwin/-/merge_requests/4113
I think that will be fixed soon :)
