### ISSUE TITLE
[Bug]: Shift + Dragging window sits on top of other window

### ISSUE THREAD

**Issue by sampbarrow** [zeroxoneafour/polonium#101]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

See other issue: https://github.com/zeroxoneafour/polonium/issues/100

It does drag within the tiles with 3+ windows now (it did not before) however when I drag one window on another, it just sits on top of it, hiding the old window, instead of swapping/moving.

This is intermittent, usually it does this, sometimes it doesn't.

### To reproduce

Open 3 windows, shift+drag one onto another.

### Expected behavior

The window that is dragged onto should reposition/retile.

### Relevant log output

```shell
See video. "TypeError" - same as my other issues but from a different line of main.js.
```

### Screenshots and videos

[Screencast_20231228_150620-1.webm](https://github.com/zeroxoneafour/polonium/assets/946543/cab527f2-8d8f-42bb-8d01-29b7bc63c043)

**Comment by FantasyPvP** [comment]
I'm having a similar issue here on plasma 6, say I open three windows like so:
![image](https://github.com/zeroxoneafour/polonium/assets/80643031/7d62fae5-3f09-41df-8a0e-9268785340a6)

if I want to use the keyboard to move the window, I can do so:
![image](https://github.com/zeroxoneafour/polonium/assets/80643031/8e315ce7-ff73-40e2-b8f7-c79343f62a43)

however, meta + shift + dragging the window doens't actually move the window:
![image](https://github.com/zeroxoneafour/polonium/assets/80643031/cccb17f6-a4f2-4542-9007-52be17db9dde)

if I then try and move the window again it does this:
![image](https://github.com/zeroxoneafour/polonium/assets/80643031/e58a1743-16ec-491a-bb19-2ec512c7e37d)

seemingly tiling across the entire screen.

**Comment by zeroxoneafour** [comment]
Probably not a relevant issue anymore
