### ISSUE TITLE
Ability to adjust the gaps between windows?

### ISSUE THREAD

**Issue by markpendlebury** [zeroxoneafour/polonium#103]
Scanning the documentation and the configuration panel in kwin i don't see a way to adjust the gaps between windows, while OOB i do have a very small gap, i'd like to increase it slightly if possible? 

To clarify, i'm talking specifically about the empty "gap" between each window and around the edge of a maximized window and the outside of my desktop.

Thanks

**Comment by yoonsangmin** [comment]
@markpendlebury This kwinscript uses default kwin snaping tiling function and you can adjust gap with default function. Press Meta+T(default shortcut) then you can see and adjust gap size on top right corner.
Anyway there's no instruction of this function and it will be nice to add this on documentation.

**Comment by markpendlebury** [comment]
@yoonsangmin Perfect thanks!
