### ISSUE TITLE
[Bug]: Two issues breaking layouts: "Focus stealing preventation" set to None and keybindings from bismuth/Kwin

### ISSUE THREAD

**Issue by pjhfggij** [zeroxoneafour/polonium#109]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

It may be worth mentioning somewhere in documentation that:
- "Focus stealing prevention" set to None 
- using shortcuts in "System Settings > Window Tiling" or  "System Settings > Kwin > Quick Tile *"
will cause polonium layouts to break. 

I've been running polonium for a few months now and only today I've realized how big of a difference it makes (switched Focus to "Medium" and only started using Polonium keybindings). 

Until today it was painful, windows broke every day, popped out of layout unexpectedly into a floating mode or generally something somewhere requested focus and ruined elaborate layouts.

### To reproduce

1. Switch `Window Management -> Window Behaviour -> Focus -> Focus stealing prevention` to None.
2. Assign shortcuts to "Quick Tile Window *" set of keybidings.
Then after a while windows should start breaking and no longer be possible to tile and empty gaps (empty tiles) should start appearing.

### Additional context

I wish I knew that when migrating from bismuth to polonium.

Sometimes you want focus setting to be low for some applications to claim focus when spawned (e.g. emacs or terminal).

**Comment by pjhfggij** [comment]
Sadly, that didn't solve the issue. There are still situations when problematic windows (e.g. Natron, some wine applications, mpv) will break layout and there is nothing you can do to restore it.

**Comment by zeroxoneafour** [comment]
Is this issue relevant to v1.0/Plasma 6?

**Comment by pjhfggij** [comment]
@zeroxoneafour I don't think so, layouts have always kept breaking, since the start (since switching from bismuth back in July).
