### ISSUE TITLE
[Bug]: Inconsistent Borders

### ISSUE THREAD

**Issue by sampbarrow** [zeroxoneafour/polonium#110]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

This is present on both 5/6. Some windows will use the rounded breeze decoration style - others will be squared off and the thin border around the edge removed. It seems completely random which window/app does what. For example, just opened konsole and chrome - chrome was squared konsole was rounded. A few minutes ago I was in settings / kwin scripts, the settings window was squared, but when i opened the polonium settings window, it was rounded.

### To reproduce

Open two windows (intermittent).

### Expected behavior

All tiled windows should have square edges or at least be the same style.

### Relevant log output

```shell
Mar 02 13:41:31 archlinux systemd[37439]: Started Konsole - Terminal.
Mar 02 13:41:31 archlinux kwin_wayland[37499]: qml: Polonium DBG: Window org.kde.konsole hooked into script
Mar 02 13:41:31 archlinux kwin_wayland[37499]: qml: Polonium DBG: Window org.kde.konsole added
Mar 02 13:41:31 archlinux kwin_wayland[37499]: qml: Polonium DBG: Adding client org.kde.konsole to desktops {"desktop":"bc38e9c1-1cf4-4c87-85ab-3a934332bcf1","activity":"13555a41-2c1a-488d-bdb1-d38051de7fc0","output":"DP-8"}
Mar 02 13:41:31 archlinux kwin_wayland[37499]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"bc38e9c1-1cf4-4c87-85ab-3a934332bcf1","activity":"13555a41-2c1a-488d-bdb1-d38051de7fc0","output":"DP-8"}
Mar 02 13:41:31 archlinux kwin_wayland[37499]: qml: Polonium DBG: Window org.kde.plasmashell removed
Mar 02 13:41:31 archlinux kwin_wayland[37499]: qml: Polonium DBG: Removing client org.kde.plasmashell from desktops
Mar 02 13:41:31 archlinux kwin_wayland[37499]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"bc38e9c1-1cf4-4c87-85ab-3a934332bcf1","activity":"13555a41-2c1a-488d-bdb1-d38051de7fc0","output":"DP-8"}
Mar 02 13:41:37 archlinux systemd[37439]: Started google-chrome-stable.
Mar 02 13:41:37 archlinux kwin_wayland_wrapper[47128]: Opening in existing browser session.
Mar 02 13:41:37 archlinux kwin_wayland[37499]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
Mar 02 13:41:37 archlinux kwin_wayland[37499]: qml: Polonium DBG: Window Google-chrome hooked into script
Mar 02 13:41:37 archlinux kwin_wayland[37499]: qml: Polonium DBG: Window Google-chrome added
Mar 02 13:41:37 archlinux kwin_wayland[37499]: qml: Polonium DBG: Adding client Google-chrome to desktops {"desktop":"bc38e9c1-1cf4-4c87-85ab-3a934332bcf1","activity":"13555a41-2c1a-488d-bdb1-d38051de7fc0","output":"DP-8"}
Mar 02 13:41:37 archlinux kwin_wayland[37499]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"bc38e9c1-1cf4-4c87-85ab-3a934332bcf1","activity":"13555a41-2c1a-488d-bdb1-d38051de7fc0","output":"DP-8"}
```

### Screenshots and videos

![Screenshot_20240302_134009](https://github.com/zeroxoneafour/polonium/assets/946543/9479e449-2c84-4362-9ab9-448ddb4e189c)

**Comment by zeroxoneafour** [comment]
Most likely related to #50. If I had to guess, this is a Kwin bug because it doesn't look like Chrome is doing anything that a maximized window would normally do in this screenshot.

**Comment by sampbarrow** [comment]
Got it. Will report to kwin.
