### ISSUE TITLE
[Bug]: Toggling full screen window in master stack layout pushes a window out of master

### ISSUE THREAD

**Issue by pjhfggij** [zeroxoneafour/polonium#113]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

Fullscreening a window (e.g. a youtube video) and toggling it back pushes it out of master tile. 

### To reproduce

Put a browser in master window.
Fullscreen a video.
toggle it back.
browser is now in a stack and another window is the master tile. if there is only two windows they get tiled horizontally if they were previously vertical.

### Expected behavior

window comes back to it's location (master)

### Relevant log output

```shell
-
```

**Comment by zeroxoneafour** [comment]
Try v1.0 and see if the issue persists.

**Comment by zeroxoneafour** [comment]
That's very strange. You might have installed the wrong version of the script, such as installing the Plasma 6 script on Plasma 5. How did you install v1.0?

**Comment by pjhfggij** [comment]
I've downloaded it from the github pre-release from 2 days ago - pretty sure it was `polonium-plasma5.kwinscript `

**Comment by pjhfggij** [comment]
Now that KDE6 was pushed into Arch and after a few difficult days when a lot of issues came up at once I can confirm that v1.0 is working - the previous issue still occurs on X11, but Wayland is fine now.

**Comment by zeroxoneafour** [comment]
Strange, but good I guess
