### ISSUE TITLE
Custom keybindings

### ISSUE THREAD

**Issue by tomaz-suller** [zeroxoneafour/polonium#116]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to port the keybindings I've customised, specifically to resize windows and to change their focus.

**Describe the solution you'd like**
A settings menu, configuration file (or instructions in the documentation if any of these already exist) on how to change the bindings.

Keybindings are on the QML files, and apparently you'd either have to read them dinamically somehow, or change the way the project is built (sorry but no experience with JS so might be saying something stupid).

**Describe alternatives you've considered**
Learning the new keybindings, which of course is not great.

**Comment by zeroxoneafour** [comment]
System Settings > Shortcuts > KWin > Shortcuts named "Polonium"
