### ISSUE TITLE
[Request] List an alternative to Bismuth window decorations in documentation

### ISSUE THREAD

**Issue by lobroc** [zeroxoneafour/polonium#117]
Hi, ever since upgrading to KDE Plasma 6, I was quite annoyed that my Bismuth window decorations were absent. As such, I went to the trouble of finding an alternative, which I have now packaged on the [AUR](https://aur.archlinux.org/packages/plasma-active-accent-frame-decorations), which is sourced from [Natalie Clarius' repo](https://github.com/nclarius/Plasma-window-decorations/tree/main) (works @ KDE).
I was thinking that it would be a nice addition to indicate this resource somewhere in the README / documentation, as in my opinion it provides an important part of the "tiling window manager feeling" in Plasma. Thanks for your consideration.

On another note, thank you very much for your work on Polonium. It's one of the main reasons as to why I enjoy using Plasma so much.

**Comment by lowne** [comment]
@lobroc thanks! Would you mind including (or making another package, given the naming, for) the titlebar variants?

**Comment by lobroc** [comment]
Hi, I've created a new package which includes all the decorations [at this location](https://aur.archlinux.org/packages/plasma-active-accent-decorations). People can therefore choose between everything or only the frame decoration. :+1:

**Comment by lowne** [comment]
@lobroc thanks a lot!

**Comment by zeroxoneafour** [comment]
The problem with mentioning anything is that then people will ask for support on it. If the script breaks, people will ask here, if people can't install it they will ask here. If I maintained the window decorations I might mention it as an option, but I don't so I don't feel qualified to put it on the readme. Even the AUR package isn't mentioned anywhere other than stating that it's unofficial maybe.
