### ISSUE TITLE
[Bug]: Can't change layout

### ISSUE THREAD

**Issue by pjhfggij** [zeroxoneafour/polonium#118]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

![image](https://github.com/zeroxoneafour/polonium/assets/161205138/8f0458fa-95dc-4055-9d5b-d5fa9ef1a0b3)
Only this layout works - before switching to KDE6 I've used master/stack layout. Toggling options doesn't do anything.

### To reproduce

Run polonium on KDE6 on Wayland

### Expected behavior

Master stack layout

### Relevant log output

```shell
-
```

### Screenshots and videos

![image](https://github.com/zeroxoneafour/polonium/assets/161205138/eb17bb77-359a-4357-9823-3b775e17f727)

**Comment by djneba** [comment]
I believe this can be closed?

**Comment by zeroxoneafour** [comment]
Yeah probably
