### ISSUE TITLE
Add shortcut to switch layouts, like Bismuth or Polonium 0.6

### ISSUE THREAD

**Issue by CarlosEkisde** [zeroxoneafour/polonium#119]
**Is your feature request related to a problem? Please describe.**

Previous versions of Polonium had a shortcut to cycle layouts per desktop. This is very useful since we're not always want to tile the windows the same way or just tile it at all.

**Describe the solution you'd like**
A shortcut to cycle layouts like Polonium 0.6. Per layout shortcuts like bismuth had would be ideal

**Describe alternatives you've considered**

**Additional context**
With the latest commit to workaround kwin crashes. I think this the final upgrade we need for Polonium 1.0 to become useable, at least for my needs. Thank you for your job on this script :+1:

**Comment by zeroxoneafour** [comment]
The cycle layout shortcut is `Meta+Shift+\` by default and the individual layout shortcuts are unset by default. Try the latest commit and see if it works for you.

**Comment by CarlosEkisde** [comment]
Hi, thank you! I tried them and they seem to properly work =D
