### ISSUE TITLE
[Bug]: Refreshed window is automatically moved to insertion point

### ISSUE THREAD

**Issue by h-d33r** [zeroxoneafour/polonium#121]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

As per the title, if I have two or more windows tiled on the same virtual desktop, whenever one is in focus and is refreshed (or something happens in that window) it is moved to the insertion point (whether right or left). 

### To reproduce

Engine: BTree
Insertion point: Right
Open two windows on the same virtual desktop (I used Dolphin and Librewolf in the logged example). Once something happens in one of the windows (e.g. I open a folder on dolphin or a website on librewolf) when that window is on the left side, the active window is moved to the right side. 

This happens in reverse when the insertion point is on the left. 

### Expected behavior

I expect the windows to stay where they are lol

### Relevant log output

```shell
Mar 13 11:33:21 archpad kwin_wayland[16089]: qml: Polonium DBG: Window org.kde.dolphin hooked into script
Mar 13 11:33:21 archpad kwin_wayland[16089]: qml: Polonium DBG: Window org.kde.dolphin added
Mar 13 11:33:21 archpad kwin_wayland[16089]: qml: Polonium DBG: Adding client org.kde.dolphin to desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:21 archpad kwin_wayland[16089]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:21 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: Window LibreWolf hooked into script
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: Window LibreWolf added
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: Adding client LibreWolf to desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: Removing client LibreWolf from desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: Adding client LibreWolf to desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:24 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:28 archpad kwin_wayland[16089]: qml: Polonium DBG: Removing client org.kde.dolphin from desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:28 archpad kwin_wayland[16089]: qml: Polonium DBG: Adding client org.kde.dolphin to desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:28 archpad kwin_wayland[16089]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:28 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:28 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:28 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:28 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:28 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:28 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: Removing client LibreWolf from desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: Adding client LibreWolf to desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: Removing client LibreWolf from desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: Adding client LibreWolf to desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:30 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:33 archpad kwin_wayland[16089]: qml: Polonium DBG: Removing client org.kde.dolphin from desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:33 archpad kwin_wayland[16089]: qml: Polonium DBG: Adding client org.kde.dolphin to desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:33 archpad kwin_wayland[16089]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:33 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:33 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:33 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:33 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:33 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:33 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: Window org.kde.dolphin removed
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: Removing client org.kde.dolphin from desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: true
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: Window LibreWolf removed
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: Removing client LibreWolf from desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 13 11:33:38 archpad kwin_wayland[16089]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8090db5b-52b1-49b7-9b23-de8d00e86340","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
```

### Screenshots and videos

[Screencast_20240313_114000.webm](https://github.com/zeroxoneafour/polonium/assets/163290351/508dd2de-487f-4913-952e-7654b82044c0)

### Additional context
Operating System: Arch Linux 
KDE Plasma Version: 6.0.1
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.7.9-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5625U with Radeon Graphics
Memory: 14.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics

**Comment by h-d33r** [comment]
This bug does not occur using the Half tiling engine. 
Here's the log output: 

`Mar 19 11:35:09 archpad kwin_wayland[82216]: qml: Polonium DBG: Window org.kde.dolphin hooked into script
Mar 19 11:35:09 archpad kwin_wayland[82216]: qml: Polonium DBG: Window org.kde.dolphin added
Mar 19 11:35:09 archpad kwin_wayland[82216]: qml: Polonium DBG: Adding client org.kde.dolphin to desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:09 archpad kwin_wayland[82216]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:09 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:10 archpad kwin_wayland[82216]: qml: Polonium DBG: Window LibreWolf hooked into script
Mar 19 11:35:10 archpad kwin_wayland[82216]: qml: Polonium DBG: Window LibreWolf added
Mar 19 11:35:10 archpad kwin_wayland[82216]: qml: Polonium DBG: Adding client LibreWolf to desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:10 archpad kwin_wayland[82216]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:10 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:10 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:10 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:10 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:11 archpad kwin_wayland[82216]: qml: Polonium DBG: Removing client LibreWolf from desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:11 archpad kwin_wayland[82216]: qml: Polonium DBG: Adding client LibreWolf to desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:11 archpad kwin_wayland[82216]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:11 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:11 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:11 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:11 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:11 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:11 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:13 archpad kwin_wayland[82216]: qml: Polonium DBG: Removing client org.kde.dolphin from desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:13 archpad kwin_wayland[82216]: qml: Polonium DBG: Adding client org.kde.dolphin to desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:13 archpad kwin_wayland[82216]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:13 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:13 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:13 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:13 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:13 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:13 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:17 archpad kwin_wayland[82216]: qml: Polonium DBG: Window LibreWolf removed
Mar 19 11:35:17 archpad kwin_wayland[82216]: qml: Polonium DBG: Removing client LibreWolf from desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:17 archpad kwin_wayland[82216]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}
Mar 19 11:35:17 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:17 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:17 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:17 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:17 archpad kwin_wayland[82216]: qml: Polonium DBG: true
Mar 19 11:35:18 archpad kwin_wayland[82216]: qml: Polonium DBG: Window org.kde.dolphin removed
Mar 19 11:35:18 archpad kwin_wayland[82216]: qml: Polonium DBG: Removing client org.kde.dolphin from desktops {"desktop":"5c17d18d-a99b-4a77-b61f-fe1419ccc21e","activity":"61ff6d02-4343-4e98-801e-0c41d3805ade","output":"eDP-1"}`

**Comment by h-d33r** [comment]
Nevermind, with the latest commits it happens on the half tiling engine as well.

**Comment by zeroxoneafour** [comment]
Strange, I could not reproduce this using dolphin and firefox. Make sure you don't have any strange kwin settings enabled outside of polonium that could be moving windows around, such as desktop switching when a window demands attention.

**Comment by h-d33r** [comment]
I had that setting enabled (don't remembering ever setting that up though). It only fixed the problem on the Half tiling engine. It still happens on Binary Tree. I also had window focus following mouse, but changing that did not help either.

**Comment by h-d33r** [comment]
As of latest build, this bug no longer occurs for me as well. I'm closing the issue.
