### ISSUE TITLE
[Bug]: Minimizing a floating window and then un-minimizing, window comes back tiled

### ISSUE THREAD

**Issue by msmol** [zeroxoneafour/polonium#122]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

Whether I manually float a window, or have a window floated due to being in the Polonium config's filter section, if I minimize the window, and then un-minimize it, it comes back tiled rather than floating. 

This is only occurring in Plasma 6. In Plasma 5 the window would come back floating.

### To reproduce

- Float a window
- Minimize that window
- Un-minimize that window
- See the window tiled rather than tiled

### Expected behavior

- Float a window
- Minimize that window
- Un-minimize that window
- See the window floating in it's original location

### Relevant log output

```shell
$ journalctl --user --no-pager -e | grep -i "polonium"
# returns empty
```

### Screenshots and videos

> [Screencast_20240313_094708.webm](https://github.com/zeroxoneafour/polonium/assets/285971/7b9c225c-a1a0-4a0b-aea8-e3285d741ae2)

**Comment by FantasyPvP** [comment]
experiencing the same thing

**Comment by CountMurphy** [comment]
Somewhat related: If I lock my screen and come back after something like 10 minutes, none of my tiled windows are "tiled" when i return (I think kwin causes a crash). The only way to re-tile my windows without closing them outright is this minimizing trick/bug.

**Comment by zeroxoneafour** [comment]
Try the latest commit again and see if anything has changed.

**Comment by msmol** [comment]
Can confirm working correctly now, thanks
