### ISSUE TITLE
Does it not work on X11 at all?

### ISSUE THREAD

**Issue by rew1nter** [zeroxoneafour/polonium#123]
I'm on KDE 6. Just installed the script and enabled from settings. 

There's literally no effect. None of the shortcuts work, no tiling whatsover. 

Is it expected?

**Comment by mgrube753** [comment]
Just logoff or reboot. Then the extension just takes effect.
Have you already set up your keybinds?
With mine, everything is working... except the Resizing Functions... i cannot resize the windows, they're all uniformly big

**Comment by RudraPS97** [comment]
I switched to wayland and it was still working.

**Comment by 0xDEAD-C0DE** [comment]
**X11 has been briefly tested but is not officially supported. If you encounter an issue running the script on X11, make sure it is reproducible in Wayland before submitting a bug report.**

This is from the projects README.rd

**Comment by zeroxoneafour** [comment]
X11 support should be working in theory but officially is not planned.

On Plasma 6 Wayland is really pretty good. I can't think of a reason to use X11. Personally, my X11 is completely broken and crashes regularly so I can't debug issues on it anyways.

**Comment by rew1nter** [comment]
>  I can't think of a reason to use X11

GPU incompatibility
