### ISSUE TITLE
[Request] Keep floating panel when no window is maximized

### ISSUE THREAD

**Issue by BenjaminMoraga** [zeroxoneafour/polonium#124]
Whenever a window is opened the floating panel inmediatly goes un-floating, this seems ok when there are no gaps between the floating windows or with maximized windows, but when gaps are enabled I think there might be an option to keep the floating panel.

Here is a screenshot:

![Captura de pantalla_20240316_200408](https://github.com/zeroxoneafour/polonium/assets/105876527/ef302d43-c7ee-4aa0-b967-817c63fff6ee)

When Polonium is not activated this can be achieved with very big gaps, but I think it should work with smaller gaps also and with Polonium activated, of course.

**Comment by zeroxoneafour** [comment]
No idea why this would happen but afaik this is out of my control. Polonium just sets up tiles, Kwin determines how widgets react to them.
