### ISSUE TITLE
How to install on KDE Neon running plasma 6.0

### ISSUE THREAD

**Issue by AJSTryingL** [zeroxoneafour/polonium#127]
Hello I have experience installing polonium on KDE Manjaro but now I switch to neon I’m having trouble installing it it’s not in the Discovery store or in the repositories. I know I can download it from github but how do I install it and make it run? please help if you can🙏🏿

**Comment by jiriks74** [comment]
Please read the README for instructions before creating an issue. There are instructions on how to do it.

> Install `node` (`npm`)
> Check that you have `kpackagetool6` installed
> Run `make && make install`

The current realease in `Releases` on Github is currently out of date, don't use it for Plasma 6.

**Comment by AJSTryingL** [comment]
Thanks you. I will try it that way

**Comment by guzman109** [comment]
You can also download the kwinscript  files from releaes and using the Install from file option in the system settings.

**Comment by zeroxoneafour** [comment]
It is also in the scripts store now, so you can install it like any other KWin script.

**Comment by guzman109** [comment]
> It is also in the scripts store now, so you can install it like any other KWin script.

Does this include the pre-releases too?

**Comment by AJSTryingL** [comment]
Thanks everyone for answering my question but I finally got it because the switch to catchy OS and then it came through in one of the updates.
