### ISSUE TITLE
Using keyboard shortcuts to switch virtual desktops makes windows unresponsive and unfocusable.

### ISSUE THREAD

**Issue by mantacid** [zeroxoneafour/polonium#128]
# Description
Switching virtual desktops via keyboard shortcuts causes windows on the previous desktop to stop responding to user input.

Currently, this bug appears on X11, but I will update this issue once I test Wayland.

## Steps to reproduce:
1. Have two virtual desktops, bind some keyboard shortcut to each one
    (I'm using ALT+1 and ALT+2)
2. Open two windows on the first desktop. Make sure they tile.
3. Hit ALT+2 to switch to the second virtual desktop. The bug is inconsistent; if you see the windows stretch vertically right before the desktop switches, then they'll be bugged.
3. Switch back to desktop 1.

## Expected results:
You can interact with the two windows after switching back to their virtual desktop.

## Observed results:
Neither window is focusable, nor can they be moved. The only way I've found to fix them is to drag their thumbnails around in the virtual desktop indicator.

**Comment by h-d33r** [comment]
This does not happen on Wayland AFAICT. I use 9 virtual desktops and switch between them all the time, never had this happen to me even once.

**Comment by mantacid** [comment]
> This does not happen on Wayland AFAICT. I use 9 virtual desktops and switch between them all the time, never had this happen to me even once.

I had switched to krohnkite some time ago, and even then the loss of window focus is an issue, albeit less frequent. I think this might be an issue with how kwin interfaces with X11.
