### ISSUE TITLE
[Bug]: Fullscreen windows do not cover the entire screen when panel bar exists

### ISSUE THREAD

**Issue by lobroc** [zeroxoneafour/polonium#129]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

When using a fullscreen application (eg. a Steam game), the window will not extend to cover the whole screen if a panel bar exists on a same screen.
This problem exists only on the Wayland session, and not the X11 one (I have tested), and only when Polonium is active on Wayland.
Certain fullscreen apps (eg. Firefox, Spotify) seem to use a different type of way of achieving fullscreen (probably not a true fullscreen).

### To reproduce

On KDE Wayland 6.0.2, Polonium 1.0b1, Arch Linux, start a Wayland session, and try to play / fullscreen any Steam game, while having a panel bar on your monitor. The window should never extend over the whole screen. It might rarely, or try to (jumps to fullscreen and back), but in the majority of cases the window does not extend the whole way.

### Expected behavior

App is completely fullscreen, as per the X11 session for example. (With the same versions of all programs.)

### Relevant log output

```shell
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Window steam_app_2357570 hooked into script
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Not tiling window steam_app_2357570
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Minimized on client steam_app_2357570 set to false
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Adding client steam_app_2357570 to desktops {"desktop":"91426cb6-dc93-4fe8-95dc-c894a26d958c","activity":"d3d97372-e012-41fd-8fa6-120c43f5becf","output":"DP-3"}
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"91426cb6-dc93-4fe8-95dc-c894a26d958c","activity":"d3d97372-e012-41fd-8fa6-120c43f5becf","output":"DP-3"}
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Fullscreen on client steam_app_2357570 set to true
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Removing client steam_app_2357570 from desktops {"desktop":"91426cb6-dc93-4fe8-95dc-c894a26d958c","activity":"d3d97372-e012-41fd-8fa6-120c43f5becf","output":"DP-3"}
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"91426cb6-dc93-4fe8-95dc-c894a26d958c","activity":"d3d97372-e012-41fd-8fa6-120c43f5becf","output":"DP-3"}
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Fullscreen on client steam_app_2357570 set to false
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Adding client steam_app_2357570 to desktops {"desktop":"91426cb6-dc93-4fe8-95dc-c894a26d958c","activity":"d3d97372-e012-41fd-8fa6-120c43f5becf","output":"DP-3"}
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"91426cb6-dc93-4fe8-95dc-c894a26d958c","activity":"d3d97372-e012-41fd-8fa6-120c43f5becf","output":"DP-3"}
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Fullscreen on client steam_app_2357570 set to true
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Removing client steam_app_2357570 from desktops {"desktop":"91426cb6-dc93-4fe8-95dc-c894a26d958c","activity":"d3d97372-e012-41fd-8fa6-120c43f5becf","output":"DP-3"}
Mar 22 19:13:15 linux kwin_wayland[32067]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"91426cb6-dc93-4fe8-95dc-c894a26d958c","activity":"d3d97372-e012-41fd-8fa6-120c43f5becf","output":"DP-3"}
Mar 22 19:13:20 linux kwin_wayland[32067]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"35e8c006-b90e-40cd-b895-b014362dbdda","activity":"d3d97372-e012-41fd-8fa6-120c43f5becf","output":"DP-3"}
```

### Screenshots and videos

Overwatch (or any other game) not fully extending, leaving the bar visible (and small borders visible across all sides of monitor). The window is effectively not fullscreen.
![image](https://github.com/zeroxoneafour/polonium/assets/91371894/5b696e97-a580-416e-997e-8e371a77eade)

**Comment by lobroc** [comment]
Nevermind, I wasn't using the nightly build, rather the stable one. The issue seems to be fixed in the newest versions, sorry about that.

**Comment by lobroc** [comment]
Nevermind, this is actually still a problem.

**Comment by root-hal9000** [comment]
I can confirm the same issue, also running nightly although I believe it was the same with v1.0b1 (I will test that). In my case I noticed when hitting F11 to make Firefox full screen, or when making a video in the browser full screen (the video controls end up behind my taskbar, since I have it on the bottom)

**Comment by zeroxoneafour** [comment]
It's strange, I have a hybrid laptop with a mux switch and I only encounter this issue on the intel gpu, not the Nvidia one. The fact that it doesn't happen on Nvidia is probably a Nvidia problem and not an Intel problem, but I'll keep looking into this.

**Comment by zeroxoneafour** [comment]
Try the latest commit and see if anything has changed

**Comment by root-hal9000** [comment]
fixed for me!
