### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by thorrrr** [zeroxoneafour/polonium#131]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

I have 3 issues on a fresh install.
1. Dolphin ignores the script it stays full page on other apps open behind any time you open it see here dolphin was the 3rd thing to open see [here](https://i.imgur.com/A1iWMCo.png)
2. Terminal if opened more than 1 time  the heights and gaps vary see [here](https://i.imgur.com/O43tkkT.png) 
3. Also what ever option in layout engine seems to make no difference on what happens on screen 

### To reproduce

Images provided 

### Expected behavior

Dolphin should obey polonium and scale to size
Gaps and heights should be uniform

### Relevant log output

```shell
https://logs.notifiarr.com/?a5be64ce8c7fc76e#Aoq88ZgoTdwtB1JWD8GiZGSfChQcBekrhMKAdKST5pcs
```

### Screenshots and videos

See above

**Comment by zeroxoneafour** [comment]
Can you reproduce this on Wayland?

**Comment by thorrrr** [comment]
I was on Wayland  Plasma 6

**Comment by zeroxoneafour** [comment]
Log says `kwin_x11`

**Comment by thorrrr** [comment]
So it does  my fault i changed and forgot to change back sorry
