### ISSUE TITLE
[Bug]: Resizing broken since "dragging" was implemented

### ISSUE THREAD

**Issue by djneba** [zeroxoneafour/polonium#134]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

When resizing windows, they tend to unsnap and turn floating. Was not the case in the beta version.

### To reproduce

Try resizing windows when two or more are tiled.

### Expected behavior

Windows resize in unison without any of them turning floating.

### Relevant log output

```shell
no log
```

**Comment by zeroxoneafour** [comment]
Yeah I just noticed this after I made the release, oopsies.

Should have a fix in a few minutes

**Comment by zeroxoneafour** [comment]
Ok test again

**Comment by djneba** [comment]
Yup. It works now. I had a crash while testing, but can't reproduce it right now. Resizing works correctly. Great job!

**Comment by zeroxoneafour** [comment]
Yeah I had a crash as well. Not relevant to dragging or resizing or any of the new features I don't think. Very strange
