### ISSUE TITLE
Add an option to always tile

### ISSUE THREAD

**Issue by djneba** [zeroxoneafour/polonium#135]
I'd like an option to disable floating all together. If I drag a window in order to move it, it would be nice that it just swaps places with another window in another tile, instead of becoming floating.

**Comment by zeroxoneafour** [comment]
https://zeroxoneafour.github.io/polonium/faq.html, see "I want to move windows using my mouse while keeping them tiled"

**Comment by djneba** [comment]
Yeah, but for some reason it doesn't swap the two windows.
I used this one ( https://github.com/kwin-scripts/kwin-tiling ) for a long time and it was working really well on Plasma 5 with x11. I preferred it over other stuff.

**Comment by zeroxoneafour** [comment]
The script has a feature where it knows where your cursor is and places dragged tiles relative to both where the cursor is and the tile your dragging it into. Are you positioning your cursor exactly where you want the tile to be?

**Comment by djneba** [comment]
When I press Shift and start dragging (active window), then the inactive window becomes floating and covers the window I'm dragging. So, I can't even see what I'm doing. Is there a keyboard shortcut I should add, or edit?

**Comment by zeroxoneafour** [comment]
This seems like a bug. Would it be possible to upload a recording?

**Comment by djneba** [comment]
Will do in a couple of hours.

**Comment by djneba** [comment]
https://github.com/zeroxoneafour/polonium/assets/69405456/37bd16d5-24df-4bc6-999f-2ba0a6b99952

**Comment by zeroxoneafour** [comment]
Make sure "Keep tiled windows below" is enabled. Also you cannot drag windows back into the root tile, this is something out of my control. It should work if you have at least 3 windows on screen.
