### ISSUE TITLE
[Bug]: Latests commits completely break tiling by dragging. Windows always gets untiled.

### ISSUE THREAD

**Issue by CarlosEkisde** [zeroxoneafour/polonium#138]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

On latest commits, after the easter release, which works well, when trying to switch tiles with another window by dragging, it won't work and the window will always get untiled. Also retiling a window by dragging to a tile isn't possible too.

### To reproduce

Open some windows, drag one of them to a border or a corner to switch position. The window will get untiled. Try to do the same to retile it. It won't work.

### Expected behavior

Retiling by dragging working  

### Relevant log output

```shell
journalctl --user --no-pager -e | grep -i "polonium"
mar 31 09:37:47 localhost kwin_wayland[24564]: file:///home/Carlos/.local/share/kwin/scripts/polonium/contents/ui/osd.qml:37: TypeError: Property 'registerWindow' of object KWin::JSEngineGlobalMethodsWrapper(0x556365e7fb30) is not a function

But probably irrelevant I'd say =P
```

**Comment by zeroxoneafour** [comment]
What KWin version do you have?

**Comment by CarlosEkisde** [comment]
`Carlos@localhost:~$ kwin_wayland --version
kwin 6.0.3
Carlos@localhost:~$ rpm -qa |grep kwin
kf5-kwindowsystem-5.115.0-1.fc39.x86_64
kf6-kwindowsystem-6.0.0-2.fc39.x86_64
kwin-libs-6.0.3.1-2.fc39.x86_64
kwin-common-6.0.3.1-2.fc39.x86_64
kwin-wayland-6.0.3.1-2.fc39.x86_64
kwin-6.0.3.1-2.fc39.x86_64
kwin-x11-6.0.3.1-2.fc39.x86_64
`
commits that break dragging are the ones after happy easter rc. This rc is correctly working.

**Comment by zeroxoneafour** [comment]
And you are holding shift so that the tile dragging indicator appears, right? I will need logs and a video if you are.

**Comment by CarlosEkisde** [comment]
> And you are holding shift so that the tile dragging indicator appears, right? I will need logs and a video if you are.

No, without holding shift. shifting windows using kwin's quick tile feature worked before and with master buid not anymore. The window tiles but like normal windows without the script, and other windows don't respect the new position of the window.

**Comment by zeroxoneafour** [comment]
Ok, I found the issue. Layout was being rebuilt when the on screen tiling overlay was present, so the tileChanged couldn't activate as it detected that the layout was rebuilding. I don't know if this is a band aid fix or not but engine no longer rebuilds when irrelevant windows are removed, so it should work now.

**Comment by CarlosEkisde** [comment]
Thank you =D Now it's properly working :+1:
