### ISSUE TITLE
Dynamic desktops support

### ISSUE THREAD

**Issue by NyaomiDEV** [zeroxoneafour/polonium#144]
**Is your feature request related to a problem? Please describe.**
Tiling window managers can usually be configured to have a dynamic amount of virtual desktops so that someone can organize more windows between those desktops. Currently this feature is missing in Polonium.

**Describe the solution you'd like**
Investigate compatibility with existing scripts (though I think none were ported to Plasma 6 yet) OR provide a native implementation within Polonium (cleaner, makes us install only one extension, more control over behaviour)

**Describe alternatives you've considered**
I am waiting for KNewStuff to get populated again...

**Additional context**
Not really applicable.

**Comment by CarlosEkisde** [comment]
It's ported indeed https://github.com/maurges/dynamic_workspaces/tree/plasma6

And it works perfectly with polonium :+1:   I think there is another script but I can't find it right now
