### ISSUE TITLE
Remove `<header>` in official site

### ISSUE THREAD

**Issue by CyrusYip** [zeroxoneafour/polonium#149]
**Is your feature request related to a problem? Please describe.**
I have to scroll over `<header>` to read the docs. When I switch tabs, I need to scroll again. It's inconvenient.

**Describe the solution you'd like**
Remove the whole `<header>`. The website will look like this:

![image](https://github.com/zeroxoneafour/polonium/assets/60951091/589bf6a4-b05a-4e66-b34f-cba014ccf0d5)

---

This content can be added under navigation bar.

![image](https://github.com/zeroxoneafour/polonium/assets/60951091/90876b86-2531-4dae-99ef-47771c710a06)

**Comment by zeroxoneafour** [comment]
I'm not a web developer, this is kind of out of my scope. Should be a simple PR if anyone wants to try it
