### ISSUE TITLE
[FR] Maximize the only window on screen

### ISSUE THREAD

**Issue by Daxtorim** [zeroxoneafour/polonium#15]
**Is your feature request related to a problem? Please describe.**
I like to have a small gap between windows just to have a little more visual separation without having to up the size of window decorations. That is not necessary when there is only a single window on screen. It also means you cannot just slam your cursor into one side to click on things on window edges but need to actually aim for the buttons, e.g. firefox tabs at the top.

**Describe the solution you'd like**
(Option to) Maximize the only window so that it fills the entire maximized area.

**Additional context**
https://github.com/zeroxoneafour/polonium/compare/master...Daxtorim:polonium:maximize-lone-window
I already tried the naive thing and added `client.setMaximize(true, true)` to `rebuildLayout()` in `src/main.ts` but that doesn't work. I mean it kind of does. The window changes state&mdash;the maximize button on the window decoration changes&mdash;but it wont actually change geometry, it still remains in its tile with gaps around it.

I also tried to put `client.setMaximize(true, true)` after the `for (... of ...)` loop (keeping track of the last client of the loop and checking that it is the only one), and that works, but that will *untile* the window and basically break tiling entirely.

Hopefully you have a better idea of where to put it and can find a solution. Thanks :+1:

**Comment by zeroxoneafour** [comment]
KWin tiling overpowers basically everything, so the maximize function would have to be similar to the fullscreen function in that it would have to disable all other tiling on the window. I definitely think I can cook something up, though.

**Comment by zeroxoneafour** [comment]
So it was quite a bit more complicated than just using `setMaximize`, but I think that I have a decent solution commited. See if it works for you. It has quite a few random bugs, but if you switch desktops to allow the layout to rebuild, it goes back to normal (making me think KWin wasn't really designed for these sorts of API-spammy scripts)

**Comment by Daxtorim** [comment]
When starting from an empty screen and opening a window it works, but when opening a second window the first one gets placed in a random geometry and any action that causes the layout to be rebuild fixes it. But from then on out it works fine as long as you don't end up with an empty screen at any point.

Kinda janky but it works I guess. I'll see over a few days if it's fine or gets annoying.

**Comment by zeroxoneafour** [comment]
The latest build has a shortcut to rebuild the layout. I don't know if I can get it any less janky with maximizing (theoretically it should work, as the layout rebuilding correctly tells me everything is working internally in the engine), but if you only need the window to fill the space and not to be "maximized", I may be able to set the root tile padding to 0 when there is only one window to fill the space.

**Comment by Daxtorim** [comment]
> but if you only need the window to fill the space and not to be "maximized"

No, I do want the window to be maximized so clicking on the border wont try to resize the window but actually click a button there.

I've been playing around with it myself in an attempt to maybe find a solution but all I managed was a workaround that is basically just calling `rebuildLayout()` again after a timer runs out ('cause no `sleep` for kwin scripts).
<https://github.com/zeroxoneafour/polonium/compare/master...Daxtorim:polonium:workaround-for-single-window-unmaximization>
It's a a hacky workaround but it works&mdash;and is better than using a shortcut to do the same thing manually. I can make a PR if you want or you can cherry-pick the commit yourself.

**Comment by zeroxoneafour** [comment]
Dang it, and I was just in the middle of writing release notes! :)

This is actually incredibly useful, as I didn't know you could use QTimer in KWin scripts (when doing things like making `new QRectF()` it always said it wasn't defined). I'll also use a QTimer to time layout rebuilding (as KWin never gets all the tiles down in time before calling layoutChanged callbacks).

Needless to say, this is an instant merge. Thanks for your help with this issue! I'll probably close it as complete once I test the changes.

**Comment by zeroxoneafour** [comment]
I also added a slider in the settings to set the callback delay. This applies to both tile changing and maximizing. Closing this issue
