### ISSUE TITLE
[Bug]: Always Increase Version Code

### ISSUE THREAD

**Issue by Glich440** [zeroxoneafour/polonium#151]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

The version code is not increased with every (pre)release, this confuses plasma and makes it refuse to install the update because it thinks it's the same version. This forces the user to manually uninstall the previous version before installing the next one.

### To reproduce

Download the latest beta and the previous beta.
Install the previous beta.
See that if you now attempt to install the current beta it fails.

### Expected behavior

The new beta simply is installed

### Log output

```shell
N/A
```

**Comment by zeroxoneafour** [comment]
It is perhaps a bit too late for this, as the next planned release is v1.0 itself. The project follows semantic versioning for non-prerelease software, it's just been a while since thats been apparent.
