### ISSUE TITLE
Drag windows and keep auto-tiling

### ISSUE THREAD

**Issue by HamletDuFromage** [zeroxoneafour/polonium#158]
**Is your feature request related to a problem? Please describe.**
With bismuth, you used to be able to drag windows around and they'd stay tiled. I found this particularly useful with multi-monitor setups. I found it faster and more intuitive than keyboard shortcuts

**Describe the solution you'd like**
An option (toggle in the settings?) that would allow it

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by HamletDuFromage** [comment]
Ah I didn't look hard enough, looks like it's already being considered https://github.com/zeroxoneafour/polonium/issues/142#issuecomment-2065659265 
I would really love that feature, this is the only thing preventing me from using polonium as it stands

**Comment by zeroxoneafour** [comment]
I think there are enough issues tracking this (#142, #135, #87, #42, #18, a whole release notes dedicated to the topic, a subsection on the faq, and countless comments about the issue) so I'll just use one of those.

Maybe I need to start posting a checklist for feature requests as well.
