### ISSUE TITLE
provide window decoration like bismuth.

### ISSUE THREAD

**Issue by soymadip** [zeroxoneafour/polonium#163]
**Is your feature request related to a problem? Please describe.**
When using polonium, it removes window title bar. 
But as it doesn't have uts own window decoration, we cannot get the window border like we got in bismuth. It help identifying the active window and also looks good too.
Also we could change the thickness of the border too. 

**Describe the solution you'd like**
Polonium should provide its own window decoration as bismuth did.
And also on top of that, if we can customise the decoration, it will be awesome.

**Describe alternatives you've considered**
As of now, i haven't seen any alternative.

**Additional context**
- Window Decoration: 
![Screenshot_2024-04-27-08-01-10-94_9c7ad408470e52983cc8816adf9ff347](https://github.com/zeroxoneafour/polonium/assets/84225810/14f9f38e-0205-492d-8d64-176a223b9b36)

**Comment by zeroxoneafour** [comment]
https://github.com/zeroxoneafour/polonium/issues?q=is%3Aissue+decoration+is%3Aclosed :upside_down_face:

**Comment by soymadip** [comment]
> https://github.com/zeroxoneafour/polonium/issues?q=is%3Aissue+decoration+is%3Aclosed 🙃

Verry sorry, i searched for similar issues but forgot to remove the is:opened filter
