### ISSUE TITLE
plasma floating panel stops floating when any windows are tiled

### ISSUE THREAD

**Issue by FantasyPvP** [zeroxoneafour/polonium#170]
I'm not sure if this is something that can be fixed from within this project, but I thought I would mention it here just so you're aware of it (as I didn't see any other issues mentioning it or anything on the website / FAQ)

usually, maximising a floating panel in plasma turns it into a normal panel, however any tiled windows on the screen also result in the panel stopping floating.

is there a way around this or should I report it upstream as a kwin issue?

**Comment by CarlosEkisde** [comment]
Floating panels become normal when touched by any window, tiled or not. This is an intended behaviour by KDE developers https://bugs.kde.org/show_bug.cgi?id=462838

**Comment by h-d33r** [comment]
Also, there is a workaround to this issue: if you go into the Tiling Editor (by default Meta+T), you'll see a padding option on the top right. If you set it to at least 20 px you'll keep your floating panel while having your windows tiled.
