### ISSUE TITLE
[FR] Keep windows tiled while moving + move window to tile with mouse

### ISSUE THREAD

**Issue by ChickenIQ** [zeroxoneafour/polonium#18]
I would like to have the option of keeping windows tiled while moving them, along with the ability to move a tiled window to another tile using the mouse.

**Comment by zeroxoneafour** [comment]
https://zeroxoneafour.github.io/polonium/faq#how-do-i-move-windows-with-my-mouse Does this solve the issue?

**Comment by ChickenIQ** [comment]
> https://zeroxoneafour.github.io/polonium/faq#how-do-i-move-windows-with-my-mouse Does this solve the issue?

No, windows automatically become floating windows when moving them.

The expected behavior is how Bismuth behaves when the option "Untile windows by dragging" is off.

**Comment by ChickenIQ** [comment]
An option to change the default behavior would be great

**Comment by zeroxoneafour** [comment]
This is not possible with the KWin tiling API, as KWin automatically untiles windows when they are moved. There is no configuration I can do to change that. By shift dragging, you should be able to achieve the end goal of moving the window back into any tile.
