### ISSUE TITLE
resizing windows by shortcut/hotkey

### ISSUE THREAD

**Issue by polair** [zeroxoneafour/polonium#19]
Hey there, thank you very much for taking on creating a more fully featured tiling script. I was pointed here by the defunct bismuth project and am glad you're around!

All tiling managers I've used have an option to resize the relationship between the tiles with shortcuts. Would you be willing to add support for this? If you are willing to take this on I'll put a bounty of $20 on it, although I'll make a donation to your development of the project regardless. 

Thanks again.

**Comment by zeroxoneafour** [comment]
Thank you for your support! Should be easy to add this to the Btree engine, Half and Three Column probably will only support resizing columns (not individual windows) with keybinds based on how the code is set up. I'll see what I can do.

**Comment by zeroxoneafour** [comment]
Try the latest commit and see if it adds what you need. If you don't like how much or how little tiles shift with each shortcut usage, you can configure it in settings. I'll document the settings and keybinds more later.

**Comment by polair** [comment]
Hey @zeroxoneafour, sorry, took me a bit to get back to this and recompile. It works exactly how I wanted, thanks much. I rebound the keys to old habits but that did it all. Thank you for being responsive and working on that feature. Give me a bit, I've never donated with KoFi. 

This was really lovely, thanks again. For me at least you have all the functionality I need. I've never developed in TypeScript but when I get some time I'll poke at your code.

**Comment by polair** [comment]
[ Thanks! Very nice, extensions and community projects are the life blood of FOSS!! ](
https://Ko-fi.com/home/coffeeshop?txid=cd0f1d6f-db7b-444f-a6a3-eeaa4c96a438&mode=public&img=ogiboughtsomeone )

**Comment by polair** [comment]
It doesn't actually affect me, but you should be aware that there is some bug that if you hold the resize key past the maximum column/row pixel dimensions at some point the column breaks and snaps from maximum size to the minimum size. I was toying with some things and found this out by doing crazy stuff. It certainly won't impact "normal" usage.

**Comment by zeroxoneafour** [comment]
Thank you so much for the donation! I'll look into patching the bug later (I assume it's in the BTree side), but I'm going to close this issue now.
