### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by piotr-dobrogost** [zeroxoneafour/polonium#194]
Where is the documentation?

**Comment by zeroxoneafour** [comment]
Where is the issue text?

**Comment by piotr-dobrogost** [comment]
> Where is the issue text?

The issue is described in the title itself so no additional text is necessary but as it seems it's required to obtain an answer I put the copy of the question in the issue text as well.

**Comment by zeroxoneafour** [comment]
Thanks! I will now reveal the cryptic location of said documentation.

On the main repo page under the description there is a link, like with most github repos. It goes to a github.io website with usage guides and an FAQ.

In case you still can't find it, try https://zeroxoneafour.github.io/polonium/

**Comment by piotr-dobrogost** [comment]
Oh, the link is in the upper right corner, in the section called _About_.
I was looking for it in the readme content itself where I believe it's present in many projects.
Thanks for help.
