### ISSUE TITLE
Vertical split with system settings not working properly

### ISSUE THREAD

**Issue by enrico223** [zeroxoneafour/polonium#2]
**Describe the bug**
There is no gap between `System settings` and any other application. It looks like `system setting` is truncated and not resized.

**To Reproduce**
1. Install Polonium
2.  Activate Polonium
3. Log in and out to make sure it works
4. Open system settings and make it split vertically as per screenshot

**Expected behavior**
There should be a gap and resizing between system setting and the other app.  

**Log**
No output from `journalctl --user --no-pager -e | grep "Polonium"`

**Screenshots**
![Screenshot_20230530_104118](https://github.com/zeroxoneafour/polonium/assets/72576597/544474cf-90ea-453c-9c0c-ff587d25f75c)

**Comment by alvesvaren** [comment]
This may be because the system settings window has a minimum window size, as a workaround you can add a window rule for that window (or all windows) where you manually override the minimum size of the window to something much smaller

**Comment by enrico223** [comment]
I'll look into it, thanks

**Comment by alvesvaren** [comment]
I tried this and it works on X11 but not on wayland for some reason.. Seems like system settings ignores my window rule for requested minimum window size when on wayland
