### ISSUE TITLE
Windows don't get untiled when maximized

### ISSUE THREAD

**Issue by CarlosEkisde** [zeroxoneafour/polonium#20]
**Describe the bug**
Windows don't get untiled when maximized, and they return after a while to their corresponding tile ignoring their maximized status. Also they continue to be maximized while insided the tile.

**To Reproduce**
1. Open some windows
2. Maximize one of them
3. Error will trigger just waiting or also faster when performing some actions

**Expected behavior**
the desired windows get maximized, doesn't return to their previous tiles, and tiled windows on the same desktop rearranges themselves to fill the space left. 

**Log**
I enabled debug mode, restart kwin and ran ` journalctl --user --no-pager -e | grep "Polonium"` and I didn't get any logs :/ Also tried logging out and in. I'm using Fedora so it's a systemd distro

**Screenshots**
![Screenshot_20230617_113847](https://github.com/zeroxoneafour/polonium/assets/24854958/5e0acab9-86d8-41fa-81ae-c6cf3fb036e1)
Telegram and firefox tiled and konsole maximized. Konsole window still counts as tiled and returns to it's original tile after a short time 
![Screenshot_20230617_120515](https://github.com/zeroxoneafour/polonium/assets/24854958/31c5b1e6-9349-4b58-8c79-2b177c198110)
See that affected window still counts as maximized after returning to it's previous tile.

**Additional context**
Obvious workaround is just manually untile the window you want to maximize before doing it. Still, both actions should perform automatically when triggering maximization.

**Comment by zeroxoneafour** [comment]
Are you running the latest master build or v0.4.0 from the store?

**Comment by CarlosEkisde** [comment]
I tried the master build, but somehow it didn't actually replaced 0.4.0 while installing without me realizing it. Now I proper installed it and it seems it's working there.
