### ISSUE TITLE
Snap windows being dragged back into tiling grid

### ISSUE THREAD

**Issue by lobroc** [zeroxoneafour/polonium#25]
**Is your feature request related to a problem? Please describe.**
I (and most likely many others) use the Meta key + window dragging with the cursor to reorganise our windows, instead of key bindings.

**Describe the solution you'd like**
It would be great if windows which have been dragged do not continue floating, but instead snap back into the tiling grid, at the "nearest" point to their current location.
Currently, you *can* move the window and hold shift afterwards to make it snap in, but you have to be very precise with your mouse placement. (and you must always press *shift*)
For a quick reference point, you could see how Bismuth does it, as it's an implementation I find ideal.

**Describe alternatives you've considered**
Potentially, keep the default behaviour as-is, but add a toggle option in the settings to enable or disable the change.

Thank you very, very much for your work :smile:

**Comment by zeroxoneafour** [comment]
Sadly, this script is not Bismuth, and can only support complex actions such as window movement within the limitations Kwin places on its tiling API.

The way Kwin implements snapping windows back into tiles is through pressing shift while moving the window. There is nothing I can do to change this. Is there a different behavior that you would prefer when snapping windows into tiles? I will probably look later into snapping into a tile position more accurately.

**Comment by lobroc** [comment]
Thanks for your quick and clear reply!

For the different snapping behaviour, the way snapping seems to work right now is that you must hover the whole window over the new tiling position, instead of just the cursor, which in my opinion would / could be more intuitive. (As soon as the cursor hovers a different tile while dragging, the window will snap to there.)
However, I'm not sure this is possible considering the aforementioned limitations. Please let me know :)

**Comment by zeroxoneafour** [comment]
I'm going to have to see if there's a way to even get the position of the cursor with the Kwin API to implement this. I'll look into it, maybe see what Bismuth did for this.

**Comment by zeroxoneafour** [comment]
The latest update added some more predictability and usefulness to dragging the windows, can you see if this at least improves the issue? I don't know if it's possible to keep the windows tiled while moving them.

**Comment by lobroc** [comment]
It feels much more intuitive and easier to snap windows to where I wanted them to be, so thank you!
I'm pretty happy with the state of things right now, so I'll close the issue :)

Best of luck to you.
