### ISSUE TITLE
Flashing windows when switching to a workspace with a single, tiled, maximized window

### ISSUE THREAD

**Issue by tianyu** [zeroxoneafour/polonium#28]
**Describe the bug**
When switching to a workspace (via KDE's 3-finger gesture) that has:
* a single window
* that is tiled by Polonium
* and Polonium's "Maximize single windows" option is enabled

The window flashes three times as if it's being retiled.

**To Reproduce**
1. Open a window, e.g. konsole, on a workspace.
2. Switch off that workspace
3. Switch back to that workspace

**Expected behavior**
No flashing

**Log**
```
Jun 21 09:25:23 excelsior kwin_wayland[1845]: file:///home/tzhu/.local/share/kwin/scripts/polonium/contents/code/main.js:8632: TypeError: Cannot read property 'tile' of null
Jun 21 09:25:23 excelsior kwin_wayland[1845]: file:///home/tzhu/.local/share/kwin/scripts/polonium/contents/code/main.js:8632: TypeError: Cannot read property 'tile' of null
Jun 21 09:25:23 excelsior kwin_wayland[1845]: js: Polonium DBG: Building layout for desktop (0, 8c0a560b-e491-4c3b-ad00-b09d841ce99f, 2)
Jun 21 09:25:23 excelsior kwin_wayland[1845]: js: Polonium DBG: Placing clients for desktop (0, 8c0a560b-e491-4c3b-ad00-b09d841ce99f, 2)
Jun 21 09:25:23 excelsior kwin_wayland[1845]: js: Polonium DBG: Building layout for desktop (0, 8c0a560b-e491-4c3b-ad00-b09d841ce99f, 2)
Jun 21 09:25:23 excelsior kwin_wayland[1845]: js: Polonium DBG: Placing clients for desktop (0, 8c0a560b-e491-4c3b-ad00-b09d841ce99f, 2)
```

**Screenshots**
If possible, add screenshots or videos to help explain your problem.

**Additional context**
KDE 5.27.6
Polonium 0.5.0

**Comment by Vaisakhkm2625** [comment]
> Try lowering the callback delay in the settings to something around 10-15 ms and see if it makes it easier to use. The reason the window flash retiles is because the maximize option uses some janky stuff to get around Kwin's slight delay. The window will always flash, but lowering the callback delay can make it unnoticeable

Is it limitation with kwin or kde api itself? if so will it get fixed when kde 6 comes out ?

( btw I was about to switch over to some twm from kde, but this wonderful extension saved me from yet another year long rabbit hole of configuring a new twm .... :*) thanks for making this )

**Comment by zeroxoneafour** [comment]
I would say limitation with Kwin, but its not a bug or anything. Kwin just cant update within the incredibly short time frame the API calls give it. For this reason, some of the API calls are distributed across time to wait on Kwin.

@Vaisakhkm2625 Did you have this bug, and if you did, does lowering the callback time to around 10ms fix it? 10ms is going to be the new default in the coming update, so I want to make sure it works.

**Comment by Vaisakhkm2625** [comment]
sorry ig wrong bug.. i was saying about this

https://github.com/zeroxoneafour/polonium/assets/68694876/d9ce8bfe-8713-45d4-a365-d279afc5f1e6


i guess this is due to limitation of the api that it cannot remember what is the layout for each desktop separately, so you are keeping track of it by your self and switching to that layout when we switch desktops right ?

**Comment by zeroxoneafour** [comment]
Yes, that's how it works right now. There is some code in place that fixed some regressions with maximizing and desktop switching in the master branch as well, so it should work even smoother.
