### ISSUE TITLE
Resizing tiles is unreliable in the three column layout

### ISSUE THREAD

**Issue by lucaspar** [zeroxoneafour/polonium#32]
**Describe the bug**

Resizing tiles in the three column mode is sometimes erratic, doing one or more of: A. tile sizes increase or decrease more than their usual step size; B. the sides are apparently switched (resizes left when pressed right and vice-versa); C. tiles don't resize at all.

**To Reproduce**

I'm not exactly sure how to reproduce it, but I notice it quite often.

1. Switch to three column layout.
2. Have at least three windows.
3. Resize each tile using resize+(left/right) commands.
4. Resizing eventually fails or does not work as expected, most notably when there are only 2 windows in the layout, but occasionally observed with 3 windows too.

Cycling layouts and going back to three column seems to fix the problem until it re-appears. Perhaps one or more variables go out of bounds after many state changes, causing the weird behavior?

**Expected behavior**
Resizing should always work when there is enough screen space.

**Log**
No new log lines as this problem was happening, even with "debug" logs enabled.

**Additional context**
Observed on Xorg, no idea if the same happens on Wayland.

**Comment by zeroxoneafour** [comment]
Xorg is not officially supported.

Can you see if the same behavior happens in Wayland?

**Comment by zeroxoneafour** [comment]
I could reproduce this on Wayland, and I think I have a fix. Can you try the latest master branch build?

**Comment by lucaspar** [comment]
Awesome, I think this nightly might have fixed it. I'll close it for now - thank you!
