### ISSUE TITLE
Polonium tiles certain popup windows

### ISSUE THREAD

**Issue by shocklateboy92** [zeroxoneafour/polonium#35]
**Describe the bug**
It seems to tile and redo the layout for transient/popup windows that really should be left as-is.

**To Reproduce**

Example 1:
1. Trigger the clipboard history by pressing `Meta` + `V`
2. It gets inserted to the layout and re-tiled.

Example 2:
1. Switch activities by pressing `Meta` + `Tab`.
2. It briefly starts shifting the windows in the current activity to make space for the switcher window that shows up on the left.
3. The activity changes, and windows get re-tiled, and this time the switcher window gets ignored
4. So it's a weird flash (even when switching from having 1 window open to another activity with also exactly 1 window open).

**Expected behavior**
- The tiled windows don't shift when popup/tooltip/transient windows show up. 
- The new transient window is left floating exactly where it would be.

**Additional context**
Following @polair's lead I'll also put a bounty on this bug. $20 seems to be the going rate :wink:. 
Let me know if that'll work. :slightly_smiling_face:

**Comment by zeroxoneafour** [comment]
After a bit of trial and error, I found that adding "plasmashell" to the process blacklist was enough to fix the two issues you mentioned. Just to be safe, I copied a bit of code from Bismuth too to check for more window types. Add that to the blacklist and try the latest master build if that didn't work.

**Comment by shocklateboy92** [comment]
[Okay, that was a much simpler/quicker fix than I expected. Thanks!](https://Ko-fi.com/home/coffeeshop?txid=29bb2df1-d6d4-46f2-943b-1b8d2231f8eb&mode=public&img=ogiboughtsomeone)
