### ISSUE TITLE
Window updates causes the layout to reset

### ISSUE THREAD

**Issue by ZenurikSD** [zeroxoneafour/polonium#38]
**Describe the bug**
Whenever you resize the windows inside a layout, any kind of update (to kwin?) makes the layout snap everything back to the default size. This happens for every action inside Firefox or opening a modal from another window for instance.

**To Reproduce**
1. Open at least two windows (Firefox and terminal)
2. Resize the layout
3. Open a new tab or click on a link inside Firefox
4. The layout will resize back to its original size.

**Expected behavior**
The layout should not resize on its own after some type of user action.

**Log**
No logs are shown when this happens

**Screenshots**
Polonium settings: https://i.imgur.com/sJTXrDm.png

**Comment by zeroxoneafour** [comment]
Found the bug, I forgot to update the QTimer implementation with the new change to using QML scripts for the entry point.

Try the latest master build and see if it works for you.

**Comment by ZenurikSD** [comment]
It seems to be fixed now. You are amazing, thank you!
