### ISSUE TITLE
Fullscreen/maximize window both loose tile position

### ISSUE THREAD

**Issue by andaag** [zeroxoneafour/polonium#43]
**Describe the bug**
Fullscreen/maximized windows both don't return to the right tile location in current main

**To Reproduce**
1. Open up a chrome window left and konsole window on right
2. Click kwin hotkey for fullscreen on the right side
3. Click hotkey to undo fullscreen
4. Konsole window is now on the left side

1. Open up a chrome window left and konsole window on right
2. Click kwin hotkey for maximize on the right side
3. Click hotkey to undo maximize
4. Konsole window is now floating

**Expected behavior**
That window returns to original position

If it's not instantly reproducible I will get debug logs, I've seen this on two computers so I assume it'll be very easy to reproduce. Running git d2a89fc

**Comment by zeroxoneafour** [comment]
This isn't a bug, but is a feature that I haven't implemented yet. The window is untiled and should be retiled when fullscreening/maximizing, but will not save it's position yet.

**Comment by zeroxoneafour** [comment]
I think I have something that could work, try out latest master commit and see if there's anything missing that you want.

**Comment by andaag** [comment]
Almost!

If I open up windows in order and name them 1,2,3,4 based on opening position.

windows 1,2,3,4 : fullscreen and then restoring works on all
windows 1,2 : fullscreen and then restoring 2 works, 1 swaps position with 2

Running with config:
```
Blacklist=krunner, yakuake, kded, polkit, telegram
InvertInsertion=true
TimerDelay=10
```

**Comment by zeroxoneafour** [comment]
When I was testing the script, I observed that the position would default to below as well. I'll have to look more into it later.

**Comment by zeroxoneafour** [comment]
I think I found the bug, can you test master again?

**Comment by andaag** [comment]
I'm still seeing the same behavior.

If I open 2 konsole windows. And maximize the right one it stays in place, but if I maximize the left one they switch position.

**Comment by zeroxoneafour** [comment]
The root tile is an edge case because of how KWin handles it differently. It should work fine other than the root tile, but I'll get something in place for the root tile as well.
