### ISSUE TITLE
"Maximize single windows" causes secondary windows to think that they're maximized

### ISSUE THREAD

**Issue by Foxinatel** [zeroxoneafour/polonium#50]
I've only been able to spot this behavior on apps that are slower to open, such as Firefox and VSCode.

When the "Maximize single windows" option is enabled, windows created after the first window will think that they're maximized when they are actually tiled. Sometimes this seems to only affect the second window that gets created, and sometimes it affects every single window after the first.

Example:
Here we can see that the second and third windows of firefox think that they're maximized (notice the slightly sharper corners on the window decorations and option to restore instead of maximize in the top right).
![image](https://github.com/zeroxoneafour/polonium/assets/75813390/e8e168e5-dd36-4f50-8770-674c98e07632)

I have tried increasing the callback delay but the behavior persists.

**Comment by zeroxoneafour** [comment]
I can only see this behavior if firefox/vscode titlebars are set to integrate with the app. When using native borders, KWin seems to think the windows are properly non-maximized. Probably a bug in firefox/vscode or KWin, or just a timing issue where the apps are too slow to update the titlebars.

Try turning on the titlebar option in the customize toolbar menu in firefox and see if that fixes it.
