### ISSUE TITLE
Desktop notifications cause screen flicker

### ISSUE THREAD

**Issue by Victor239** [zeroxoneafour/polonium#51]
**Describe the bug**
Any desktop notifications cause the screen to flicker as the notification goes away.

**To Reproduce**
1. Install KDE Connect Android app, pair it with your PC and use the "send ping" feature.
2. After the notification goes away, your app windows will flicker.

**Expected behavior**
No flicker

**Comment by Managor** [comment]
Can confirm this. It seems to be a select few windows that experience it. Could it be an xwayland thing? https://www.youtube.com/watch?v=vgmar_KbGqM

**Comment by zeroxoneafour** [comment]
Does this happen in the master build as well? If it does, try adding "plasmashell" to the blacklist and see if that helps.

**Comment by Managor** [comment]
plasmashell is already in the filter processes list

**Comment by HimDek** [comment]
> plasmashell

Adding "plasmashell" to filter processes did solve this for me. Shouldn't "plasmashell" be present in the list by default?

**Comment by zeroxoneafour** [comment]
It's present in the list by default in the master build. Believe #35 was when I added it.
