### ISSUE TITLE
Tile a fullscreen window if a window is getting tiled behind it 

### ISSUE THREAD

**Issue by Managor** [zeroxoneafour/polonium#53]
**Describe the bug**
Demonstrative video: https://youtu.be/SNASDOdwOWY
It is often frustrating when a window tiles behind another fullscreen window. Thus the window on front should also tile when something opens behind it. The most obvious example is a file picker portal that opens behind a browser. If no changes to the layout were made before the new window closes, the old window should move back to fullscreen.

**To Reproduce**
1. Put a window in full screen
2. Open another window that untiles in the background

**Expected behavior**
The fullscreened window should also tile to allow for viewing of the new window

**Video**
https://youtu.be/SNASDOdwOWY

**Comment by zeroxoneafour** [comment]
Ok, I added something sort of like this to the master build. It's really buggy, but according to the logs the window does do everything it should. This may not be possible due to KWin limitations, but I'll keep evaluating it for v0.6.0.
