### ISSUE TITLE
Strange positioning with multiple monitors

### ISSUE THREAD

**Issue by peterhoeg** [zeroxoneafour/polonium#54]
**Describe the bug**
Sometimes opening a 2nd application causes the first application to show in the middle of the screen.

I'm seeing this *sometimes* on 2 machines with multiple monitors. I don't have logs yet but I will get logs and add them here. For now I just wanted to raise the issue in case others see something similar.

I have 2 machines:
1. desktop with 2 monitors
2. laptop that sometimes is connected to a dock with either 1 or 2 external monitors (so a total of 2 or 3)

When the laptop is not connected to a dock/external monitor I have *no* problems.

**To Reproduce**
1. On a machine with more than 1 monitor
2. Launch an application (which one doesn't matter) - it opens maxized as expected
3. Launch a 2nd application
4. The 1st application is now shown centered with the 2nd application taking up the space on the right (as expected) but overlapping the 1st application

**Expected behavior**
The 1st application to take 50% on the left and the 2nd application to take up 50% on the right

**Log**
I will share this, so feel free to ignore this for now.

**Screenshots**
I'll add this

**Additional context**
NA

**Comment by zeroxoneafour** [comment]
Does this happen with master build? QTimer had a bug that was fixed in the master, so it may be a timing issue.

**Comment by peterhoeg** [comment]
I have not tried with master but I did notice a qtimer error message. I'll
let you know after 0.5.2 is released?

**Comment by zeroxoneafour** [comment]
I'm planning to release 0.5.2 tomorrow, with whatever I have right now plus maybe a bit extra. The QTimer regression is causing a lot of problems that should've been resolved if I had released 0.5.2 maybe a week ago.

**Comment by peterhoeg** [comment]
The problem no longer exists with v0.5.2
