### ISSUE TITLE
Features listed in usage guide are absent from shortcuts; settings menu

### ISSUE THREAD

**Issue by salperinlea** [zeroxoneafour/polonium#6]
https://zeroxoneafour.github.io/polonium/usage.html lists the setting "default engine" and the keybind "Polonium: Cycle layouts"; they are absent from my installation, however.

I am using Arch, fully updated. KDE 5.27.5, Polonium v0.3.0; Installation was done through "Get New Scripts".

**Comment by zeroxoneafour** [comment]
That documentation is for master branch, ie. version v0.4.0 as of now
