### ISSUE TITLE
Tabs (groups)

### ISSUE THREAD

**Issue by danielkrajnik** [zeroxoneafour/polonium#67]
**Is your feature request related to a problem? Please describe.**
It would be really cool if at some point polonium allowed windows to be grouped into a single window (tabbed). Bismuth never had this functionality, but some new window managers are implementing this ([hyprland](http://wiki.hyprland.org/hyprland-wiki/pages/Configuring/Dispatchers/#grouped-tabbed-windows)).

**Describe the solution you'd like**
You should be able to collapse multiple windows into a single window and navigate between them inside a single window.

**Describe alternatives you've considered**
[tabbed](https://tools.suckless.org/tabbed/) (suckless), but it caused strange errors in zathura and needed to be invoked at the start rather than "at runtime".

**Comment by zeroxoneafour** [comment]
I can see a few reasons why this probably wouldn't work out, at least on a script contained basis.
1. Tabbed uses the xembed protocol, which does not support Wayland. Fortunately, there is a Wayland protocol (foreign) that supports roughly the same thing. Unfortunately, KWin scripts have no access to either protocol.
2. Interaction with the tile manager would be more complex. With dedicated tiling wms, you can set modifier keys to put windows into tabs (ex. Ctrl-Meta-Drag). KWin only supports normal dragging and shift dragging, and those are both used to arrange windows.
3. I don't know if QML widgets can be arranged in a way to provide a tabbing interface to a tab group. If they could, it would probably be fairly complex.

I don't see support for this feature in the future, especially as a part of this script. Closing this issue
