### ISSUE TITLE
Rotate Layout

### ISSUE THREAD

**Issue by danielkrajnik** [zeroxoneafour/polonium#68]
**Is your feature request related to a problem? Please describe.**
Bismuth was able to rotate layout (e.g. three columns become three rows). It would be awesome if polonium at some point in the future had a similar functionality.

**Describe the solution you'd like**
You press a shortcut (e.g. Meta+R) and windows "rotate":
````
1 2 
3 4     
````

````
3 1
4 2
````

There should be also a reverse action (rotate back, e.g. Meta+Shift+R)

**Comment by zeroxoneafour** [comment]
This normally wouldn't be possible, but I'm considering a rewrite of the internal engine to utilize a virtual tile system instead of updating the tiles in real time, which should make this feature easier to implement. I'll see if I can fit this feature into it as well. This virtual tile system may also fix #65 and possibly some other bugs.

**Comment by zeroxoneafour** [comment]
I would probably use the settings dialog for this instead of a shortcut, but I may implement both.

**Comment by danielkrajnik** [comment]
Fantastic, thank you. You are saving us all with this project!

**Comment by zeroxoneafour** [comment]
I ended up not implementing the virtual retile system, but I did add the rotate layout feature in a way. You can toggle rotation between 0 and 90 degrees in the settings menu per-desktop or globally.

**Comment by danielkrajnik** [comment]
That's great news, thank you very much! I've been looking forward for this feature (won't miss reading logs on horizontally split windows).

I can't seem to see this option in the settings yet though. I've switched to AUR package, which has the latest commit merged:
![image](https://github.com/zeroxoneafour/polonium/assets/15096799/c2ab7a46-dc04-4ee1-b85f-ec30677fa989)

I've tried to restart kwin as well and forgot that it's no longer x11, so ended up crashing everything (`kwin_x11 --replace & disown`), but after restart the option still wasn't there?

**Comment by zeroxoneafour** [comment]
Try uninstalling the AUR package and install master from the kwinscript file provided by Github actions.

**Comment by danielkrajnik** [comment]
I've just tried that, but still no new menu options show up. I will confirm it again after reboot.
![image](https://github.com/zeroxoneafour/polonium/assets/15096799/a20294ec-8e28-4252-bb01-01f203386175)

**Comment by zeroxoneafour** [comment]
If you press the change settings shortcut (default `Meta+Shift+\`) does an option to rotate the layout for the current desktop pop up?

**Comment by danielkrajnik** [comment]
thanks, I've tried it as well, but nothing happened. `Meta+shift+\` doesn't seem to exist on my kde though - unless I've overridden it at some point. Does it correspond to one of the function in shortcuts menu?
![image](https://github.com/zeroxoneafour/polonium/assets/15096799/925d1f22-c8e2-433a-bfa9-80b6568dd82f)

**Comment by zeroxoneafour** [comment]
My bad, according to KDE the shortcut is `Meta+|` because the normal shortcut with Shift is collapsed based on the keyboard layout. The shortcut won't appear if the settings don't show the rotate layout option though, so try uninstalling the script, logging out, and then reinstalling it from the latest Actions build.

**Comment by pdf** [comment]
Can a keybind for this be added? I frequently want to change orientation on an ad-hoc basis, just depending on what I happen to be doing at the time, and having to pop a menu then use the mouse to toggle a checkbox and save is a pretty painful workflow for that scenario.

**Comment by danielkrajnik** [comment]
Have you tried adding it to the "Window Tiling > Rotate or Rotate (Reverse)" . I don't know though if these entries were created by Polonium or some of the previous tiling window plugins that I use.

**Comment by pjhfggij** [comment]
> Have you tried adding it to the "Window Tiling > Rotate or Rotate (Reverse)" . I don't know though if these entries were created by Polonium or some of the previous tiling window plugins that I use.

[shortcuts need to be reset](https://github.com/zeroxoneafour/polonium/issues/115#issuecomment-1986932051)

**Comment by pjhfggij** [comment]
breakages are back - every time I click on a link from thunderbird to open it in librewolf and invisible tiles appears and split the layout in half.

**Comment by ItMeCorban** [comment]
Is there a way we can set the layout rotation per screen?
