### ISSUE TITLE
Set floating windows to be in the background by default

### ISSUE THREAD

**Issue by danielkrajnik** [zeroxoneafour/polonium#69]
**Is your feature request related to a problem? Please describe.**
Bismuth had a very useful option that allowed to set any floating windows to be by default in the background.

**Describe the solution you'd like**
Add such an option to polonium.

**Describe alternatives you've considered**
Right now none. Floating windows are always on top. Not sure how to change that behavior.

**Comment by zeroxoneafour** [comment]
Have you tried turning off Keep tiled below?

**Comment by danielkrajnik** [comment]
Thank you very much for the fast response. I can't see to find this option in polonium settings? Is it located somewhere else?
![image](https://github.com/zeroxoneafour/polonium/assets/15096799/c1f0bb0c-039b-4a37-b75f-7300afa376d9)

**Comment by danielkrajnik** [comment]
Sorry, I've never been this embarrassed my whole life. You are right, this option was just there!

Thank you again for the amazing work and such a fast response.
