### ISSUE TITLE
[Bug]: Losing focus when opening new window (Xwayland)

### ISSUE THREAD

**Issue by danielkrajnik** [zeroxoneafour/polonium#70]
### Before you make the issue, confirm that

- [ ] You are running the master build from GitHub actions - not sure, installed from KDE's settings (New Scripts)
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

When opening new window for some Xwayland applications (noticed only emacsclient) focus stays on the current application (active window) instead of switching to the newly created window.

### To reproduce

`emacs --daemon && emacsclient --create-frame`

### Expected behavior

Focus is put on the newly created window (most other Wayland applications seem to work this way)

**Comment by zeroxoneafour** [comment]
The engine doesn't handle focus between windows. If the bug only happens with a select number of XWayland apps, most likely the apps don't send the correct signals to KWin to recieve focus.

**Comment by danielkrajnik** [comment]
thank you for explaining, that appears to be correct. Sorry, so many moving parts it's sometimes hard to know where to look.

**Comment by danielkrajnik** [comment]
Just to confirm, this was caused by the "Focus stealing prevention" setting in plasma's "Window Behaviour".

Can't believe it took me this long to come up with this...
