### ISSUE TITLE
[Bug]: Kwin stutters when script is active

### ISSUE THREAD

**Issue by ZenurikSD** [zeroxoneafour/polonium#71]
### Before you make the issue, confirm that

- [x] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

My desktop (specifically kwin-wayland) stutters a lot when doing anything with the script enabled: The mouse cursor stops for half a second repeatedly.
I have confirmed it does not happen with the script disabled.

### To reproduce

1. Using wayland, enable the script
2. Restart your user session
3. Use your desktop like normal
    a. Stuttering happens around every 10 seconds

### Expected behavior

Desktop should not stutter

### Relevant log output
Whenever I have the script enabled, this appears on `journalctl`, almost always at the same time a stutter happens:
```shell
jul 30 10:21:08 **** plasmashell[181576]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
jul 30 10:21:08 **** kwin_wayland[181446]: qml: Polonium DBG: Adding and not tiling org.kde.plasmashell
jul 30 10:21:08 **** kwin_wayland[181446]: qml: Polonium DBG: Adding and not tiling org.kde.plasmashell
```

### Additional context
**System info:**
Operating System: Solus 4.4
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.3.12-241.current (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

**Comment by andaag** [comment]
Random theory of something I've also seen : Is this in electron/webkit based apps, or the whole desktop? Because I've seen random freezes with vscode myself, and I ended up changing vscode without wayland mode (code --ozone-platform=x11) - but I never connected that it might be related to this script.

**Comment by ZenurikSD** [comment]
The whole desktop, even when interacting only with "native" windows like dolphin

**Comment by zeroxoneafour** [comment]
I don't really know why this could happen. I personally don't experience any issues with it. It seems like the script ignores retiling plasmashell, so there's nothing really going on in the backend that would cause lag.

Is it just the mouse cursor that stutters, or does the display stutter too?

**Comment by ZenurikSD** [comment]
I'm not sure. Never seen a video or game stutter, only when interacting with the desktop. I did reset the script's settings to default and that helped a bit though.
