### ISSUE TITLE
Add uninstall instructions

### ISSUE THREAD

**Issue by nonetrix** [zeroxoneafour/polonium#72]
**Is your feature request related to a problem? Please describe.**
When I uninstall the script, it seems to modify configurations etc. And KDE acts strangely like no title bars or windows refusing to go on top of other windows

**Describe the solution you'd like**
Uninstall instructions or some way to make the changes not stay when turned off or removed

**Describe alternatives you've considered**
¯\_(ツ)_/¯

**Additional context**
![PXL_20230801_030859706~3](https://github.com/zeroxoneafour/polonium/assets/45698918/ef8149ae-f50a-481f-8dc6-63a9b645dc3c)

**Comment by nonetrix** [comment]
I have tried 
1. Deleting everything in `.config` that references plasma or kwin
2. Deleting cache files
3. Logging in and out

**Comment by CarlosEkisde** [comment]
You seem to use x11 and kwin has crashed in there. Try running it on the terminal "`kwin_x11 --replace`"

**Comment by nonetrix** [comment]
That seemed to at least get my window title bars back back I have to do this everytime restart plasma is anyway, and I am still having the issue of windows refusing to overlap each other. Also didn't see the section about testing on Wayland too, I will do that and update you. Just keep in mind I am a Nvidia user so it might not be 100% accurate to everyone else

**Comment by nonetrix** [comment]
Wayland appears to work as before, but again it being Nvidia it's still not ideal

**Comment by CarlosEkisde** [comment]
> That seemed to at least get my window title bars back back I have to do this everytime restart plasma is anyway, and I am still having the issue of windows refusing to overlap each other. Also didn't see the section about testing on Wayland too, I will do that and update you. Just keep in mind I am a Nvidia user so it might not be 100% accurate to everyone else ![PXL_20230801_163147079](https://user-images.githubusercontent.com/45698918/257582164-767ed74e-3f57-417e-a891-c53a54e50427.jpg)

For some reason on x11 KDE is not loading kwin as part of the startup process. (or maybe actually loads but immeditely crashes after that) I'm not the adequate person to debug this problem or if it has to do with this script. But uninstallation should process should be just removing using the scripts configuration panel without any additional step. If that doesn't work for some reason, it should be considered a bug.

**Comment by nonetrix** [comment]
Well that didn't work, so I guess this is a X11 specific issue perhaps. Up to you if you want to fix it I guess since X11 is not officially supported by your admission which I can understand. But Wayland on NVIDIA is still not at a point where I want to use it mainly because of graphical issues that Nvidia has been radio silent on fixing as usual, probably will get a AMD card before they fix it smh

**Comment by zeroxoneafour** [comment]
Very strange, the script should be completely managed by KWin. This comes with uninstalling properly as well. There may be some residual scripts running, but all of that should go away on a reboot. This is probably a KWin bug, especially if there is inconsistent behavior between X11 and Wayland.
