### ISSUE TITLE
Make the separate shortcuts for each tiling scheme available.

### ISSUE THREAD

**Issue by coordinatio** [zeroxoneafour/polonium#74]
**Is your feature request related to a problem? Please describe.**
The workflow I've got used with Bismuth relies on the ability to quickly switch between tiling schemes. For example: sometimes you work with several windows tiled side-by-side and want to switch all your attention to a single window, giving it all the available screen space. With Bismuth, you just hit the predefined key that triggers the monocle layout and voilà, you have the only window maximized. When you are done, you just hit the another shortcut that triggers the Quarter layout and you once more have your windows side-by-side. For me, it seems a super convenient way of interaction with the desktop. 

**Describe the solution you'd like**
It would be nice to have the ability to assign shortcuts that trigger the specific layouts to have the ability to quickly switch between them.

**Describe alternatives you've considered**
Currently, you have to cycle between all the layouts to get to the one you need. Takes a lot of time and in case of mistake to stop cycling in time it takes even more time as you can cycle only in one direction only. Makes the interaction slower and less cool.

**Comment by zeroxoneafour** [comment]
In the master build, there is a shortcut to open a UI that can set the engine and certain settings. Does that at least partially solve the issue? I don't want to add too many shortcuts to the script.

**Comment by coordinatio** [comment]
> In the master build, there is a shortcut to open a UI that can set the engine and certain settings. Does that at least partially solve the issue?

Not much, because the shortcuts are about the speed of interaction with the desktop. The workflow I've described implies frequent switches between the layouts. Inability to do that fast kills the whole idea.

**Comment by coordinatio** [comment]
May be just exposing layouts switch through dbus will do the trick? It is dead easy to convert such exposure into shortcuts and allows not to grow the number of shortcuts the script supports directly.

**Comment by zeroxoneafour** [comment]
You can't expose methods on DBus, as scripts can only make calls to preexisting services. I suppose I could add shortcuts for switching engines, but they wouldn't have default bindings.

**Comment by zeroxoneafour** [comment]
Can you see if the latest actions build from the local branch works for you? I want to hold off merging into master until v0.6.0 release.

**Comment by coordinatio** [comment]
I've just switched from the patched for wayland bismuth to polonium from the "local" branch. The first impression: works exactly as needed. Thank you!

I will use this version with my day-to-day tasks and see if I can provide you with any additional feedback.

**Comment by hexclover** [comment]
Hello, may I ask about the status of this change? It seems the `local` branch is gone, and while `docs/usage.md` mentions layout cycling, searching for `cycle` in the code turns up nothing.

**Comment by zeroxoneafour** [comment]
This was added a while back but has been removed. It may be added back in a later release of v1.0.
