### ISSUE TITLE
DWM like Master-Stack Layout

### ISSUE THREAD

**Issue by domsch1988** [zeroxoneafour/polonium#77]
I was wondering if something like this would be possible. A Master-Stack layout with a hotkey to move the active client to the master pane. Ideally with a configurable Master width.

**Comment by zeroxoneafour** [comment]
In most cases, the Half layout can serve as a more flexible alternative to this layout. Is there an issue with the Half layout that makes it hard to use?

**Comment by Thaodan** [comment]
> In most cases, the Half layout can serve as a more flexible alternative to this layout. Is there an issue with the Half layout that makes it hard to use?

Is there already a keybind to make a window the "master" window?
