### ISSUE TITLE
Half but for vertical monitor?

### ISSUE THREAD

**Issue by Pachin0** [zeroxoneafour/polonium#79]
Hello. I love this script but there are no layouts that work for a vertical monitor. I was thinking that perhaps the half layout rotated 90 degrees could work. Do you think this could be implemented easily?

**Comment by zeroxoneafour** [comment]
Implemented in master with the rotation feature. 0.6.0 will probably release with it soon as well.

**Comment by Pachin0** [comment]
Thank you so much. Very useful.
