### ISSUE TITLE
[Feature] Keep floating windows above

### ISSUE THREAD

**Issue by Nano-Ocelot** [zeroxoneafour/polonium#8]
**Is your feature request related to a problem? Please describe.**
The option "keep tiled windows below" creates an issue where fullscreening windows doesn't put them above panels as is the expected behavior.

**Describe the solution you'd like**
An alternative "keep floating windows above" as is used in Bismuth and Krohnkite will fix this problem while also essentially providing the same functionality.

**Comment by zeroxoneafour** [comment]
Fullscreening windows should untile them and put them above tiled windows. If you use the integrated fullscreen function of some apps, it may not work. However, when using the KDE fullscreen shortcut you should not experience any problems.

How are you enabling fullscreen, and what should happen that doesn't?

**Comment by Nano-Ocelot** [comment]
That must've been it, yeah. I can't reproduce it. I can't remember which app was having the issue but it was likely the built-in fullscreen of that app causing it. It appears to be functioning correctly.
