### ISSUE TITLE
[Bug]: Menu should be floating

### ISSUE THREAD

**Issue by Quoteme** [zeroxoneafour/polonium#83]
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

When using the `Application Menu` titlebar button under `Appearance > Window Decorations > Titlebar Buttons` in the KDE systemsettings (as seen in figure 1), the menu which appears when clicking this button on a window that supports it (for example KDE-Konsole) gets tiled like a regular window, while it should be a floating menu (see: figure 2). The expected result is in figure 3.

| Figure 1 |
|--------------|
| ![image](https://github.com/zeroxoneafour/polonium/assets/6796009/120e786e-6411-4dec-8f2c-0ac6fddbb62c) |

| Figure 2 |
|--------------|
| ![image](https://github.com/zeroxoneafour/polonium/assets/6796009/25453868-d2cf-4f72-9076-58552bf7acb7) |
| 1. this button was pressed |
| 2. this window gets tiled, although it should be floating |

| Figure 3 |
|-------------|
| ![image](https://github.com/zeroxoneafour/polonium/assets/6796009/40785923-45ec-4352-a171-c4eae7271d79) |

### To reproduce

Add the `Application menu` titlebar button and click it while in a tiled layout (like for example the binary space partitioning one).

### Expected behavior

The  menu should be sized correctly and next to the mouse when the button has been clicked. Basically, do not alter the menu window at all when in a tiling state.

### Relevant log output

```shell
Sep 01 18:08:27 nixos kwin_wayland_wrapper[2489]: file:///home/luca/.local/share/kwin/scripts/polonium/contents/code/main.mjs:8858: TypeError: Type error
```

This is all I have. Not sure if helpful? Everything runs fine though.
```


### Screenshots and videos

See posts above.

### Additional context

OS: NixOS 23.05.20230830.8418899 (Stoat) x86_64
Host: ASUSTeK COMPUTER INC. GV301QE
Kernel: 6.3.5
Uptime: 26 mins
Packages: 5052 (nix-system), 7413 (nix-user), 16 (flatpak)
Shell: zsh 5.9
Resolution: 1920x1200, 3440x1440
DE: Plasma (Wayland)
WM: kwin
Terminal: alacritty
CPU: AMD Ryzen 9 5900HS with Radeon Graphics (16) @ 3.300GHz
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
GPU: NVIDIA GeForce RTX 3050 Ti Mobile
Memory: 7316MiB / 15402MiB

**Comment by zeroxoneafour** [comment]
Wayland has some issues with figuring out what floats and not due to the lack of the net WM window type protocol. Can you enable debug mode and try getting another log where the dialog was tiled?

**Comment by pjhfggij** [comment]
Three more examples:
- pinentry program - on X11 it was floating and on Wayland it's tiling, which I think it shouldn't:
![image](https://github.com/zeroxoneafour/polonium/assets/161205138/c87a460a-afb4-4eaa-ac80-765979970a1c)
- gimp popup:
![image](https://github.com/zeroxoneafour/polonium/assets/161205138/36a566ed-50e1-4891-862e-121135ca015d)
- zenity
