### ISSUE TITLE
Polonium v1.0-beta — issues and discussion

### ISSUE THREAD

**Issue by polair** [zeroxoneafour/polonium#89]
Hello there. I've installed your new version from the github-built kwinscript. I initially intended to make a beta package for Arch but I ran into some issues building it myself. While it built and installed, the script didn't show up properly in the menu. There seems to be two missing files in the v1.0 branch from the previous version, that are somehow present in your "nightly" build that I'm guessing are related? 

```
qml/settings.qml
qml/dialog.qml
```

In general v1.0 seems to work very well, when it's working. Resizing, tiling, floating, etc et al are fairly bug free. That is until one of two things happens. Either adding or removing a display, or toggling on-off the script. At these points it seems to lose count of the windows on a display and how they are tiled and a lot of strange things happen. Here is a video example, in this I've removed a monitor and then tried to open a new terminal window. I open and close it and "float" it to show the current affect:

![polonium](https://github.com/zeroxoneafour/polonium/assets/55159216/5afae841-51c2-4933-9269-4edb6b00a3cf)

Thanks for going for a code rewrite to clarify things! I'll look through the code tonight.  The only thing that fixes the issue I've described above is restarting kwin as far as I can tell.

**Developer Edit**
Pinning this thread for general discussion about v1.0 beta not tied to a specific issue or feature request

**Comment by zeroxoneafour** [comment]
The nightly build actually isn't v1.0. There is a separate GitHub action building it. It seems like the action is having a bug with uploading the artifact, so I'll have to fix that.

**Comment by zeroxoneafour** [comment]
Artifact building is working now, if you try the new version it will likely be much more buggy right now. Just a warning

**Comment by polair** [comment]
Got it! Thanks for that. I was able to use the generated kwinscript, although I still can't build directly from the branch for some reason. It looks like, from your recent commit, that you know that sizing doesn't work :)

It seems, at least for my 3-monitor setup that adding windows and closing them generally works very well. So I would say that you're killing it for alpha-level product. The most obvious bug that makes it fairly unusable, is that whenever a window is moved from one display to the next it seems that polonium is unaware. Steps to reproduce:

Open window1 and window2 on screen1. Move window1 to screen2 and open window3. Windows 1, 2, and 3 are all pulled back over to screen one in a 3-window tile configuration that you would expect if they had all been opened there. 

I unfortunately haven't got to dig too deeply into your code so I can't be of much more help than that. But this is the major bug I see. It also crops up when closing windows sometimes. It seems that whatever object storage you're using for the associated windows isn't being updated properly for some events.

**Comment by zeroxoneafour** [comment]
Screens and activities have not been implemented yet. I should have this done very soon.

**Comment by zeroxoneafour** [comment]
I added handlers for screens/activities to clients, they tenatively should work now.

**Comment by zeroxoneafour** [comment]
@acegallagher The script runs a lot of things on kwin startup, so its important to restart kwin after starting the script.

**Comment by acegallagher** [comment]
Hmmm. I've gone through a few iterations of testing and things seem to be fairly chaotic for multi monitor (my desktop) but behaves fine if I'm on my laptop with no external screens. I'm using the build that has the date/time "25 Oct 02:53 2023"

How can I provide useful information on the issues? For the multi-monitor setup, I restart kwin and open two windows with my mouse on the same screen and they remain untiled. If I float and unfloat them repeatedly, using a key shortcut, the eventually fall in line and tile properly.

**Comment by k4ever** [comment]
I started testing the v1.0 build today, but I ran into a major issue. I use the Plasma Drawer (https://store.kde.org/p/1973454/) widget as my default applications menu. Your v1.0 build treats this menu as a window and tiles it, making it too small and useless. I can't figure out how to prevent this from happening. I can't find the command to open a plasmoid so I can exclude it from tiling. Is there any way to stop applications menus and other plasmoids from tiling in v1.0?

**Comment by k4ever** [comment]
I would also like to request the ability in v1.0 to tile windows top and bottom when the screen is rotated. I use tiling primarily on my Surface Pro tablet, which has a 3:2 aspect ratio and screen autorotation. I turn the screen to portrait mode to read books and occasionally watch some of those YouTube videos that are annoyingly shot on an iPhone in portrait mode (seriously, do iPhone users not know who to rotate their phones to landscape mode when shooting a video????). When tiling in portrait mode, the best use of screen real estate is top and bottom, not side by side. GNOME 45 autotiling extension does this automatically when the screen is rotated. I would love to see this in KDE Plasma.

**Comment by zeroxoneafour** [comment]
Right now, the script does not have support for blacklisting popup windows or blacklisting by tag. I should have this done by this weekend. Layout rotation will not be automatic, but there will be a live configuration option for it (like the current master build) on release.

**Comment by k4ever** [comment]
> Right now, the script does not have support for blacklisting popup windows or blacklisting by tag. I should have this done by this weekend. Layout rotation will not be automatic, but there will be a live configuration option for it (like the current master build) on release.

Will the live configuration be touchscreen compatible?

**Comment by zeroxoneafour** [comment]
It will be a keybind, so if you can find a way to activate it with the touchscreen it could be compatible.

**Comment by k4ever** [comment]
How often do you plan to make changes to 1.0 beta? 

I just pulled a copy 2 days ago. The issue I had with the applications menu/Plasma Drawer getting treated as a window and tiled is gone. I'm now having weird issues with maximizing and minimizing windows. If I have two windows opened and tiled (of course), and I decided to minimize one of the windows, the other one doesn't get maximized. I have to completely close the other window for the remaining one to maximize. Hope that makes sense..

**Comment by zeroxoneafour** [comment]
Minimizing and maximizing are wip on v1.0. My exams are next week and Ill work on the project much more after.

**Comment by k4ever** [comment]
> Minimizing and maximizing are wip on v1.0. My exams are next week and Ill work on the project much more after.

Good luck on your exams! I finished up and graduated from my university this time last year, so I know how much stress your under.

**Comment by k4ever** [comment]
I hope your exams went well. I'm currently testing Plasma 6 on a separate partition on one of my computers. Are you going to support Plasma 6 anytime soon?

**Comment by zeroxoneafour** [comment]
I just spun up a plasma 6 vm and can see that the script is completely broken. Knowing kwin scripting documentation theres probably nothing as nice as a migration guide or anything provided. I'm sure that the migration process will completely break backwards compatibility though so for now theres nothing I can really do but wait for release.

**Comment by Granitosaurus** [comment]
I've tried giving it a shot on `v1.0` branch commit `dbb86e5e829d8ae57caf78cd3ef0606fdc1fbca5` and this desktop:
```
KDE Plasma Version: 5.27.10
KDE Frameworks Versions: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.1.65
Graphics Platform: Wayland
```
and journal is filled with type related errors but I can't trace it back to what's causing this:
```
$journalctl -b -r 
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Placing clients for desktop (0, e8a96e51-cd71-44bc-8414-3d1f0ccc883b, 4)
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: file:///home/dex/.local/share/kwin/scripts/polonium/contents/code/main.mjs:8623: TypeError: Type error
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: file:///home/dex/.local/share/kwin/scripts/polonium/contents/code/main.mjs:8623: TypeError: Type error
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: file:///home/dex/.local/share/kwin/scripts/polonium/contents/code/main.mjs:8623: TypeError: Type error
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: file:///home/dex/.local/share/kwin/scripts/polonium/contents/code/main.mjs:8623: TypeError: Type error
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: file:///home/dex/.local/share/kwin/scripts/polonium/contents/code/main.mjs:8623: TypeError: Type error
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Building layout for desktop (0, e8a96e51-cd71-44bc-8414-3d1f0ccc883b, 4)
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Placing systemsettings in QRectF(3440, 0, 3440, 2880) with direction (below, right, horizontal)
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Adding and tiling systemsettings
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Placing clients for desktop (0, e8a96e51-cd71-44bc-8414-3d1f0ccc883b, 4)
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: file:///home/dex/.local/share/kwin/scripts/polonium/contents/code/main.mjs:8623: TypeError: Type error
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: file:///home/dex/.local/share/kwin/scripts/polonium/contents/code/main.mjs:8623: TypeError: Type error
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Building layout for desktop (0, e8a96e51-cd71-44bc-8414-3d1f0ccc883b, 4)
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Placing systemsettings in QRectF(0, 0, 6880, 2880) with direction (below, right, horizontal)
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Adding and tiling systemsettings
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Placing clients for desktop (0, e8a96e51-cd71-44bc-8414-3d1f0ccc883b, 4)
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Building layout for desktop (0, e8a96e51-cd71-44bc-8414-3d1f0ccc883b, 4)
Dec 20 15:32:02 nixos kwin_wayland_wrapper[1866]: qml: Polonium DBG: Adding systemsettings to desktop (0, e8a96e51-cd71-44bc-8414-3d1f0ccc883b, 4)
```
There are only 2k~ lines on that main.mjs file so it's hard to traceback what causes the `TypeError` here. Any ideas how to debug this?

**Comment by zeroxoneafour** [comment]
Keyboard shortcuts are wip right now. The script has a lot of moving parts, so I wouldnt recommend turning it off or on without restarting kwin. Shortcuts are one of the last major blockers before v1.0 beta can release though, it should be ready sometime soonish.

**Comment by Lippiece** [comment]
I have this problem when updated from plasma 5:
```
Cannot import selected script.
The new package has a different type from the old version already installed.
```

<details><summary>Screenshot</summary>

![Screenshot_06_21-35-04](https://github.com/zeroxoneafour/polonium/assets/47634624/b5748d46-d668-4c73-9e02-0457903d1337)

</details> 

Can't find any mention of polonium in the filesystem.

**Comment by Roknor** [comment]
Check your ~/.local/share/kwin/scripts . You will have to remove the old polonium folder manually. That's what fixed it for me.

**Comment by zeroxoneafour** [comment]
Weird that Plasma doesn't have any migration code set up for old scripts. If there was an old script installed, you would think it would delete it if it was no longer compatible but I guess not? May have to add a section to the FAQ about migration.

**Comment by Lippiece** [comment]
> Check your ~/.local/share/kwin/scripts . You will have to remove the old polonium folder manually. That's what fixed it for me.

I had to use `kpackagetool6 -i Downloads/polonium-plasma6.kwinscript` and then `sudo mv ~/.local/share/kwin/scripts/polonium/ /usr/share/kwin/scripts/`, and then reboot.

**Comment by zeroxoneafour** [comment]
If you installed it globally (ex. AUR package) then you would have to look in `/usr/share/kwin/scripts/`. Note that the AUR package is unofficial.

**Comment by HamletDuFromage** [comment]
I can't seem to enable the script. When I click the checkbox in the kwin script settings, I get this:

```
~ took 13s ❯ journalctl --user --no-pager -e | grep -i "polonium"
march 09 14:55:24 microwave kwin_wayland[20961]: kwin_scripting: Component failed to load:  (file:///usr/share/kwin/scripts/polonium/contents/ui/main.qml: Library import requires a version, file:///usr/share/kwin/scripts/polonium/contents/ui/main.qml: Library import requires a version)
```

Any idea of what it may be?

**Comment by zeroxoneafour** [comment]
@HamletDuFromage Qt 6 doesn't require versioned imports, Qt 5 does I think. Make sure you're running the right build for your system.

**Comment by HamletDuFromage** [comment]
> @HamletDuFromage Qt 6 doesn't require versioned imports, Qt 5 does I think. Make sure you're running the right build for your system.

Ah yeah my bad, for some reason I was under the impression I was using plasma 6 I use a bleeding edge distro. Works the plasma 5 version

**Comment by KirilOkun** [comment]
> > Check your ~/.local/share/kwin/scripts . You will have to remove the old polonium folder manually. That's what fixed it for me.
> 
> I had to use `kpackagetool6 -i Downloads/polonium-plasma6.kwinscript` and then `sudo mv ~/.local/share/kwin/scripts/polonium/ /usr/share/kwin/scripts/`, and then restart Plasma.
> 
> The `.local/share/kwin/scripts/` was empty, even when I had the error.

I tried the above suggestions but Polonium still doesn't show up under Window management - KWin Scripts.   Any other suggestions?

**Comment by SamuXzX** [comment]
> > > Check your ~/.local/share/kwin/scripts . You will have to remove the old polonium folder manually. That's what fixed it for me.
> > 
> > 
> > I had to use `kpackagetool6 -i Downloads/polonium-plasma6.kwinscript` and then `sudo mv ~/.local/share/kwin/scripts/polonium/ /usr/share/kwin/scripts/`, and then restart Plasma.
> > The `.local/share/kwin/scripts/` was empty, even when I had the error.
> 
> I tried the above suggestions but Polonium still doesn't show up under Window management - KWin Scripts. Any other suggestions?

I don't see it either, but I think that like other scripts it needs to have a release for Plasma 6 to be shown there. We just have to wait for the next release.

**Comment by jiriks74** [comment]
Hello.
First of all - great work! It's working quite well for me!

But I got some issues that prevent me from using this further.

- The shortcut to cycle through tiling engines is no longer there
- The shortcut to trigger floating mode on a window is no longer present
- The retile shortcut doesn't retile the window
- When I open Firefox/Jellyfin/... and enter fullscreen mode the panel is still visible

I appreciate all the work you've put into this.

**Comment by hp27596** [comment]
Hello. Thanks for all your work. Is Monocle layout missing from the latest plasma 6 build?

**Comment by zeroxoneafour** [comment]
@hp27596 Monocle layout has been added in the latest build. To cycle windows forward, use the up/right insert keys, to cycle back use down/left.

**Comment by gebrk** [comment]
@zeroxoneafour Thanks for readding the monocole layout, is it deliberate that window switching via alt+tab doesn't raise the selected window, only cycling with the insert keys does?
Also is all windows untiling when cycling through the kwin layout known behaviour?

**Comment by zeroxoneafour** [comment]
Both of these are intentional. The KWin layout is the "floating" layout with the default KWin tiling added as well, so all windows are naturally in an untiled state. If you tile windows in the KWin layout, they will stay tiled when switching. The way that the monocle layout works is that it puts all the windows in a single tile and moves around how the windows are raised. If a window is raised above others through means other than the shortcuts, it will have its raised position reset when the layout is rebuilt.

**Comment by zeroxoneafour** [comment]
I doubt the monocle layout could ever be made to support that without larger changes to the tiling system that would make the other engines more complex than necessary (every engine would need a new hook into a window being focused). It's doable but may lead to unecessary breaking changes with the other engines.

To insert new windows above, set your insertion point to "Left" in the Polonium settings. If you only need it to be left on monocle layouts if you're using other layouts as well, I recommend dbus-saver and per-desktop settings.

**Comment by lgjint** [comment]
The latest version of polonium fixes drag out of a tile, thanks for your hard work!

But I've encountered some small bugs where the width of the window being dragged out is forced to be the width of the screen.

And can the developer consider implementing the window in the btree tile to retain the resized height/width instead of fixed height/width division?

**Comment by zeroxoneafour** [comment]
@lgjint There's nothing that can be done about the window resizing when dragged out, all of the geometry outside of tiled windows is done by KWin.

Does the BTree layout not retain its size when resized through the Meta+T menu?

**Comment by zeroxoneafour** [comment]
Also probably closing this issue as Polonium v1.0 is out of beta right now. Any issues should be reported, all feature requests will be delayed until the release of v1.1.

**Comment by lgjint** [comment]
> @lgjint There's nothing that can be done about the window resizing when dragged out, all of the geometry outside of tiled windows is done by KWin.
> 
> Does the BTree layout not retain its size when resized through the Meta+T menu?

I mean to keep its original width in the tile, I went about this in a very stupid way before. https://github.com/zeroxoneafour/polonium/issues/107#issuecomment-1997013423 😂

After adding a new window in a btree tile, it will revert to a fixed height-width split either by meta+t or by dagging on the edge of the window to resize it.

**Comment by zeroxoneafour** [comment]
Can you open a separate bug report issue about the BTree not properly resizing?
