### ISSUE TITLE
Sometimes windows fail to tile

### ISSUE THREAD

**Issue by andaag** [zeroxoneafour/polonium#9]
**Describe the bug**
So this is a bit of a weird one. This happens sporadically, and I'm having a hard time reproducing it. I'm also not succeeding in getting logs.

**To Reproduce**
1. Open a konsole window <it tiles correctly>
2. Open vscode - it open as a normal window. - It's not a floating window, because if I click on konsole it goes under the konsole window.
3. Try to use my hotkey for tiling on it - it doesn't work
4. If I close the konsole window and then tile the vscode window it tiles correctly.
5. If I reopen konsole everything tiles as I would expect.

If I do the exact same steps afterwards then it does tile correctly. Could it be something with the window itself remembering its position in the wrong place?

**Expected behavior**
Normal tiling

**Log**
I have tried to enable logging in the latest version from kde store, and I'm still not getting any logs. (I rebooted afterwards).

**Screenshots**
I don't think a screenshot would help here, but once we figure out the lack of logs I'll get a proper trace and or a gif.

**Additional context**
Latest fedora 38, plasma 5.27.5. I have a gut feeling that this is easier to reproduce after logging out and in again, but lets focus on getting logs and then I can keep going until I can reproduce.

**Comment by zeroxoneafour** [comment]
Very strange, I could repeatedly reproduce this using only vscode by attempting to move the untiled vscode window into a tile. I know that this behavior is definitely vscode's fault, but I suppose I'll have to look into fixing it as vscode is most likely going to commonly be used with this extension.

I have a rough idea of what the issue is (vscode is failiing to bind with a tile and is instead completely ignoring all cues from Kwin to move into the tile) but honestly this seems more like a Kwin and vscode issue. Still have to look into it more.

**Comment by zeroxoneafour** [comment]
Also noticed that this behavior happens with Discord and Heroic Games Launcher too. I guess all electron apps may be affected?

**Comment by andaag** [comment]
Yeah I think that makes sense. I've seen this since then in slack as well, and I think I saw it once on chrome itself - but I didn't report that as I have a really hard time reproducing it. It was very clearly reproducible with vscode though.

That might also be a workflow thing 🤔. Slack I open and have sitting in an activity. Chrome I open new windows all the time, but not new processes. Vscode I open a new process of quite often.

**Comment by zeroxoneafour** [comment]
Bug has been reported [here](https://bugs.kde.org/show_bug.cgi?id=470759)

**Comment by zeroxoneafour** [comment]
So I did a lot of debugging, and I fixed the problem. Kwin can still crash, though, so I'm keeping the Kwin bug report open. Try the latest master actions build and see if it fixes anything.

**Comment by andaag** [comment]
I've run 0c2a10b for a few days now and I would say its drastically better.
