### ISSUE TITLE
[ISSUE]: First windows tiled show title bar

### ISSUE THREAD

**Issue by GjMan78** [zeroxoneafour/polonium#93]
I set Polonium to never show the window decorations but when I go to place them side by side, the border with the title always appears on the first one.

I don't understand how to disable this.

I don't know how to reproduce this, I probably activated a shortcut but I don't know how to fix it.

I put a screenshot to show the problem.

![image](https://github.com/zeroxoneafour/polonium/assets/116692121/1c57f442-5f32-411e-98d7-672d1e9768ac)

![image](https://github.com/zeroxoneafour/polonium/assets/116692121/c21cda3f-6310-4eda-bdf7-7f82115b66de)

**Comment by zeroxoneafour** [comment]
Have you tried using the new version of the script (v1.0)?

**Comment by GjMan78** [comment]
I cloned the repo and installed from source...

**Comment by zeroxoneafour** [comment]
Try using v1.0 branch
