### ISSUE TITLE
[Feature] Border visibility -> No border maximized

### ISSUE THREAD

**Issue by HanabishiRecca** [zeroxoneafour/polonium#94]
We now have "Maximize single windows" option. It would be nice to be able to also hide borders for them specifically.

**Comment by cig0** [comment]
Hmm, all windows here open fully maximized without gaps on the edges :thinking: 

My settings are as follows:

![image](https://github.com/zeroxoneafour/polonium/assets/394089/cf4e8048-0422-48f9-995d-dbeba77d24f9)

And my syspecs:

![image](https://github.com/zeroxoneafour/polonium/assets/394089/8809c577-83ec-48f6-80ae-d11e25445c58)

_I'm currently using the **proprietary totally bullshit Nvicrap drivers** until Kernel 6.7 hits my distro, which hopefully will improve Nouveau performance, especially the refresh rate currently lock at 60 Hz with these drivers_

**Comment by HanabishiRecca** [comment]
Borders include the titlebar too. Even using default Breeze window decoration you should have it.
How exactly it works depends on the decoration plugin used though.

**Comment by cig0** [comment]
I'm pretty sure there aren't any borders whatsoever when having a single application per virtual desktop with its window maximized. Otherwise, I should see the background leaking through the cracks like it happens when having at least two tiled windows in the same VD :slightly_smiling_face:

**Comment by HanabishiRecca** [comment]
I don't know what you are trying to achieve by saying that. 0 width borders are invisible. Gaps between tiled windows are intentional extra padding by design.

But regardless of what you see, Breeze tricks do not apply to other decorators. By borders I mean entire window decoration with titlebar. Like if you enable "no borders all" mode.

**Comment by cig0** [comment]
Oh I see @HanabishiRecca I was thinking about the _gaps_, not the border windows :man_facepalming:

**Comment by zeroxoneafour** [comment]
So no borders for maximized windows but borders on tiled windows? Doesn't have much to do with tiling, this may be better off in a separate script. May look into it / make the script myself

**Comment by HanabishiRecca** [comment]
Yeah, pretty much every tiling window manager can do that. And Bismuth does that too.
Occupying the space by borders when there is only single window on the screen seems pointless.

**Comment by zeroxoneafour** [comment]
It may be fixed now, I didn't really change anything other than fixing maximization triggers
