### ISSUE TITLE
Rotation for Specific Monitors

### ISSUE THREAD

**Issue by ZenHWu** [zeroxoneafour/polonium#96]
I am having issues using polonium with a combination of horizontal and vertical monitors, I would like to configure it so that only one screen has rotated tiling.

This way my horizontal monitors can still tile side by side, while my vertical monitor can tile vertically.

Thanks!

**Comment by zeroxoneafour** [comment]
Should be supported by using the individual desktop settings through `Meta-Shift-\` or however your shortcuts are configured.

**Comment by ZenHWu** [comment]
thanks for the help zeroxoneafour! I can confirm this works, however, how do I keep this configuration persistent across restarts?

**Comment by zeroxoneafour** [comment]
zeroxoneafour/dbus-saver
